#!/usr/bin/env bash
# candidate-control.sh — 候选人管理 candidate control SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="候选人管理 candidate control"

usage() {
  cat <<EOF
candidate-control.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./candidate-control.sh             # interactive
  ./candidate-control.sh --dry-run
  ./candidate-control.sh --json
  ./candidate-control.sh --explain
  ./candidate-control.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "候选人管理 candidate control" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**首次通话：建立动机档案，而不是卖岗位**——问清楚：为什么现在开始看？上一次换工作是什么触发的？下一份工作必须解决什么问题？除了你，还有谁参与这个决定（配偶、家人、导师）？什么会让你留下？**把答案写下来，后面每个节点都回到这份档案。**"
  "**每个节点之前对齐预期**——面试前告诉他会遇到谁、大概问什么、这一轮的重点是什么；面试后 24 小时内取得他的反馈**并在他要求你之前先给他客户侧的反馈时间预期**（「客户说三天内给，我周四之前一定回你，即使还没有结果也会告诉你」）。**做到承诺的时间点，比反馈本身更重要。**"
  "**中途反复核对决策要素**——每两周问一次：「你现在还在看哪些机会？」「和上次比，你的优先级有变化吗？」。变化本身就是最重要的信号。"
  "**防止终面前跑掉**——最常见的三个原因：等待期太长、对某个未被回答的疑虑（老板、稳定性、地点）越想越大、以及另一家给了更快的 offer。对应的三个动作：主动缩短或解释等待、**把疑虑显性化并去找答案**（而不是安抚）、以及提前知道竞争节奏。"
  "**offer 前的「预谈薪」**——在正式 offer 之前，用条件式问法确认「如果是 X + Y，你会接受吗」，得到明确答复再推动客户走审批。这一步是猎头侧防止 offer 被拒的主力动作，也是第 9 条工作流里正式接受率虚高的成因 (evidence: [T03-S046])。"
  "**离职挽留的预演**——见第 10 条工作流。核心是让候选人**在低压力时先想清楚自己的理由**，并把它写下来。"
  "**入职后跟进**——30/90 天各一次。这既是保证期内的风险管理，也是下一次 BD 与推荐的来源。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "candidate-control-walkthrough"
fi
