#!/usr/bin/env bash
# counter-offer-no-show.sh — counter-offer 与 no-show 防范 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="counter-offer 与 no-show 防范"

usage() {
  cat <<EOF
counter-offer-no-show.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./counter-offer-no-show.sh             # interactive
  ./counter-offer-no-show.sh --dry-run
  ./counter-offer-no-show.sh --json
  ./counter-offer-no-show.sh --explain
  ./counter-offer-no-show.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "counter-offer 与 no-show 防范" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**在初筛就问离职动机的真实内容**——「如果你现在的公司给你加 20%，你还会走吗？为什么？」。答案是「不会」的人，后面大概率会被留下；答案里如果只有钱，风险最高。"
  "**在终面之后做一次「预演」**——把即将发生的事逐个说出来并让候选人预先给出应对：「你提离职那天，你老板可能会说三件事：加钱、给你换项目、说这边有个大机会给你。你打算怎么回？」把回答**写下来**。预演的作用不是操纵，而是让候选人在低压力时先想清楚，避免在高压场景里做出他自己都不认同的决定。**伦理边界见第 17 条工作流。**"
  "**offer 前的「预谈薪」**——在正式 offer 发出前，用条件式问法确认「如果是 X，你会接受吗」。得到明确「会」之后再走审批。这一步是猎头侧防止 offer 被拒的主力动作，也是第 9 条工作流里接受率虚高的成因，两面都要认。"
  "**辞职当天与之后 72 小时是最高危窗口**——安排当天联系一次，第二天再一次。这段时间候选人独自面对老板挽留、同事情绪、以及「是不是做错了」的自我怀疑。"
  "**pre-boarding（入职前管理）**：签署后 24 小时内发欢迎信 + 未来直属上级本人的一条消息；一周内寄出设备或办理账号；两周内安排一次非正式的团队见面（喝咖啡/线上 30 分钟）；入职前 3 天确认第一天的时间地点与到岗流程；入职前 1 天再确认一次。"
  "**反向留出体面的退出通道**——如果候选人真的决定留在原公司，好好收尾。他会是三年后的候选人，也可能是明年的客户。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "counter-offer-no-show-walkthrough"
fi
