#!/usr/bin/env bash
# intake.sh — intake 需求诊断会 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="intake 需求诊断会"

usage() {
  cat <<EOF
intake.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./intake.sh             # interactive
  ./intake.sh --dry-run
  ./intake.sh --json
  ./intake.sh --explain
  ./intake.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "intake 需求诊断会" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**会前 30 分钟做功课**——LinkedIn 官方 intake 清单明确要求招聘方在会前先做内外部调研：查薪酬基准、查这类岗位的典型技能、查这个岗位过去谁做过、为什么走的，并据此预估各阶段耗时 (evidence: [T03-S001])。带着数字进会，比空手进会能问出完全不同的问题。"
  "**开场先问「为什么现在要这个人」**——LinkedIn 清单第一段的原话方向是问清「这个岗位的背景与业务需求是什么」「它和你团队的成长怎么对齐」，并要求用人经理给出**已存在的、他认为合适的人的样本档案**（example profiles）(evidence: [T03-S001])。要样本档案是这一步性价比最高的动作：用人经理说不清楚的标准，往往能用「这三个人像，这两个人不像」指出来。"
  "**把愿望清单逼成可证伪的成功标准**——问「这个人入职后**前 90 天 / 前 120 天**要给公司带来的三件事是什么」。这是 intake 问题库里被各家反复列出的核心问题 (evidence: [T03-S011])。写不出三件事，说明这个岗位还没想清楚，不该开。"
  "**切「必须有 vs 最好有」并当场定死**——LinkedIn 清单把这一条单列，理由写得很直白：区分不开，后面的环节就会被主观判断和偏见填满 (evidence: [T03-S001])。操作上强制排序：让用人经理把候选条件排成有序列表，然后问「如果这个人只满足前三条，你面不面？」——不面就说明第四条其实是必须有；面，就说明第四条以后全是最好有。"
  "**对齐薪酬区间与市场现实**——把内部批的区间和外部基准并排放在同一页上。这是唯一能在会上、而不是在第一个 offer 被拒时，暴露「预算与市场差 30%」的时机。注意合规：美国多州禁止询问候选人薪酬历史（加州 Labor Code § 432.3 是最常被引用的一条，且要求应候选人要求提供该岗位的薪酬区间）(evidence: [T03-S012])——这意味着**薪酬锚点必须在 intake 会上由公司先定，不能留到面试时靠问候选人现薪来定**。"
  "**对齐流程与承诺**——LinkedIn 清单要求当场确认：这个岗位的优先级、第一批简历的评审时间、决策轮的时间、状态更新的方式、面试是集中排（batch）还是零散排、用人经理的休假安排 (evidence: [T03-S001])。"
  "**会后 24 小时内发纪要，一周后开复盘会**——LinkedIn 清单把「发一封要点总结邮件 + 一周后再开一次会 + 之后每周或每两周 check-in」写成固定动作 (evidence: [T03-S001])。一周后那次会的真正作用是**用前 10 份真实简历校准标准**，而不是走过场。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "intake-walkthrough"
fi
