#!/usr/bin/env bash
# off-limits.sh — off-limits 与职业道德 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="off-limits 与职业道德"

usage() {
  cat <<EOF
off-limits.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./off-limits.sh             # interactive
  ./off-limits.sh --dry-run
  ./off-limits.sh --json
  ./off-limits.sh --explain
  ./off-limits.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "off-limits 与职业道德" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**在签约时就把三件事写死**：(a) **范围**——是整个客户集团、还是只有下单的那个法人主体/事业部；(b) **期限**——从委托开始到结束后多久（这是最常争议的一项，**没有统一的行业数字，必须在合同里写明**）；(c) **例外**——主动来找你的候选人（inbound）算不算、公开招聘信息的应聘者算不算。"
  "**建立可执行的封锁机制**——把 off-limits 公司名与起止日期录入 CRM，做成触达前的强制校验。**口头记住的封锁名单等于没有封锁名单。**"
  "**不挖自己安置过的人**——这是本行几乎不成文但极硬的一条：你把一个人放进去，就不能再把他挖出来。**期限同样需要在合同或内部政策里写明**，实务上常见的做法是与保证期或更长的期限挂钩，但**没有统一标准**。"
  "**利益冲突的披露**——同时服务两家直接竞争的客户、或顾问本人与候选人有个人利害关系，都必须事前披露 (evidence: [T03-S055])。"
  "**保密与信息使用**——从客户、候选人、参考人处获得的信息只能用于本次委托，不得用于其他委托或个人利益 (evidence: [T03-S055])。**把 A 客户的组织图卖给 B 客户，是这一条最典型的违反方式。**"
  "**对候选人的义务**——AESC 的《Candidate Bill of Rights》给出了可直接自检的清单：告知委托关系、提供岗位概况、及时更新进度、**被淘汰时主动通知**、公平评估、保密、以及**「被遗忘权」——候选人可以要求把自己的名字从公司数据库中删除** (evidence: [T03-S054])。"
  "**数据合规**——中国大陆侧，猎头持有的候选人信息属于个人信息，处理须有合法性基础（通常是单独同意），并须响应删除请求 (evidence: [T03-S034])；机构本身的经营还须符合《人力资源市场暂行条例》与《人力资源服务机构管理规定》的许可与行为要求 (evidence: [T03-S056], [T03-S057])。**2026 年 4–7 月的全国专项整治把「未经许可擅自经营」「虚假招聘」列为重点** (evidence: [T03-S020])。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "off-limits-walkthrough"
fi
