#!/usr/bin/env bash
# offer.sh — offer 设计与谈判 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="offer 设计与谈判"

usage() {
  cat <<EOF
offer.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./offer.sh             # interactive
  ./offer.sh --dry-run
  ./offer.sh --json
  ./offer.sh --explain
  ./offer.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "offer 设计与谈判" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**锚点在 intake 会上就定好，不在谈判桌上现定**——见第 1 条工作流。谈判时才发现区间不够，只有两个结局：加价失控或候选人流失。"
  "**薪酬透明立法已经改变了起点**——截至 2026 年，美国有多个州与华盛顿特区要求在招聘信息中披露薪酬区间或应要求披露，各州的触发条件、是否必须写在岗位帖上、罚则差异都很大 (evidence: [T03-S036])。科罗拉多州的《同工同酬法》要求雇主在**每一个职位机会的通知中善意披露**时薪或年薪金额或区间，并说明福利与申请方式；违反的罚款为每次 500–10000 美元 (evidence: [T03-S037])。**远程岗位可能触发候选人所在州的义务，而不只是公司所在州** (evidence: [T03-S036])。实务后果：**你的区间已经是公开信息，「先让候选人报价」这套打法在这些辖区基本失效**，谈判重心从锚定转向结构设计与非现金要素。"
  "**薪酬历史是法律禁区**——美国多州禁止询问候选人薪酬历史，加州 Labor Code 432.3 同时要求应候选人要求提供该岗位的薪酬区间 (evidence: [T03-S012])。合法且更有用的问法是问**期望**、问**决策要素**（「除了钱，还有什么会影响你的决定」）。"
  "**口头 offer 的风险**——口头 offer 在很多市场会被理解为承诺；一旦口头给出后又调整条件或撤回，声誉损失是立刻的。更稳的顺序是：**先做「如果我们给你 X，你会接受吗」的条件式探询（不构成 offer），拿到明确答复后再走审批、再发正式书面 offer**。注意这会把正式 offer 的接受率人为推高到 95%+，**这个数字漂亮但没有信息量**——统计时应把口头探询的拒绝也计入分母 (evidence: [T03-S038])。"
  "**书面 offer 必须写清的项**：岗位名称与级别、汇报对象、工作地点与远程政策、起始日、基本薪酬与发放周期、浮动薪酬的计算与发放条件、股权/期权的数量、行权价、归属节奏与加速条款、签字费与返还条件、试用期与考核标准、**附条件条款**（背调、竞业审查、体检、工作许可）、offer 有效期。"
  "**给候选人合理的决策时间**——48 小时的「爆炸 offer」会赢得当下、输掉口碑。业内常见做法是 3–7 天，高管岗位更长。这是惯例判断，不是来源结论。"
  "**offer 到入职之间的空窗管理**——这是流失最集中的一段（见第 10 条工作流）。至少要做：签完当天引荐未来直属上级、两周内一次非正式的团队接触、发放设备/账号前置、以及一个明确的「有任何变化随时找我」的联系人。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "offer-walkthrough"
fi
