#!/usr/bin/env bash
# outreach.sh — 主动触达 outreach SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="主动触达 outreach"

usage() {
  cat <<EOF
outreach.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./outreach.sh             # interactive
  ./outreach.sh --dry-run
  ./outreach.sh --json
  ./outreach.sh --explain
  ./outreach.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "主动触达 outreach" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**分层，不要一视同仁**——把名单切成 A（值得手写，占 20–30%）、B（半模板 + 一句真实的个性化）、C（纯模板，接受低回复率）。个性化的真实成本是 8–15 分钟一封，这决定了你只能对 A 层做。LinkedIn 官方数据：**单独发送的 InMail 比批量群发回复率高约 15%** (evidence: [T03-S017])。"
  "**第一封信写短**——LinkedIn 对 2021 年 5 月至 2022 年 4 月数千万封企业招聘官 InMail 的分析显示：**少于 400 字符的信回复率比平均高 22%**，800–1200 字符低 6%，**超过 1200 字符低 11%**；而现实中只有 10% 的信少于 400 字符，46% 超过 800 字符 (evidence: [T03-S017])。**短信件之所以有效，一半原因是它稀缺。**"
  "**第一封信的四件事**：为什么是你（一句真实的、只对这个人成立的理由）、这是什么机会（岗位 + 一句为什么值得看）、我要你做什么（明确的小请求：15 分钟通话，不是「发份简历」）、退出通道（「不合适回一句不用了就好」）。"
  "**跟进节奏**——LinkedIn 数据：**65% 的回复在 24 小时内到达，90% 在一周内** (evidence: [T03-S017])。这意味着**一周没回就该发第二封**，而不是等两周。常见节奏是 D0 / D3–4 / D10 / D21，第二封换角度（换一个卖点或换一个渠道），第三封是收尾信（「我先不打扰了，需要时随时找我」）。三封之后停止，把人放回 CRM 等下一个窗口。"
  "**发送时机**——LinkedIn 数据：周一略高于平均，周五低 4%，周六低 8%（最差）；但 15% 的信仍在周五发、2% 在周六发 (evidence: [T03-S017])。"
  "**记录**——每一批触达都要记 4 个数：发出量、打开/已读量、回复量、愿意深聊量。没有这四个数，第 3 条工作流的漏斗倒推就是空的。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "outreach-walkthrough"
fi
