#!/usr/bin/env bash
# reference-check.sh — reference check 与背调 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="reference check 与背调"

usage() {
  cat <<EOF
reference-check.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./reference-check.sh             # interactive
  ./reference-check.sh --dry-run
  ./reference-check.sh --json
  ./reference-check.sh --explain
  ./reference-check.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "reference check 与背调" 工作流。

入门 SOP 共 11 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**要 3 位，且指定类型**——一位直属上级、一位平级、一位下属（若带过团队）。只让候选人随便给三个人，得到的必然是三份推荐信。"
  "**问什么才有信息量**——避免「他怎么样」这类只能得到礼貌回答的问题。有信息量的问法是："
  "**按 scorecard 的字段记录**，而不是写一段印象。"
  "**候选人在场的一种变体**：Topgrading 的做法是让**候选人自己去约**前上司做背调（TORC，Threat of Reference Check），这既是它最有效的机制，也是被批评最多的地方 (evidence: [T03-S030])。**保留分歧**：支持者认为它能让候选人在整个面试过程中更诚实；反对者认为它把压力不当地转嫁给候选人，且候选人只会约愿意说好话的人。"
  "**告知与授权必须是独立文件**——FCRA 要求雇主在获取背调报告前，向候选人提供**清晰醒目的书面告知**，说明将获取背调报告，并取得其**书面授权**；该告知必须是**独立文件**，不能混在求职申请表里 (evidence: [T03-S031])。"
  "**不利行动是两步，不是一步**——若打算因报告内容不录用：**第一步（pre-adverse action）**先给候选人一份报告副本 + 一份《FCRA 权利摘要》，让他有机会查看并解释；**第二步（adverse action）**做出决定后再发通知，须包含出具报告的机构名称/地址/电话、声明该机构未参与决策且无法解释原因、以及候选人有权就报告的准确性提出异议并在 60 天内免费再取一份报告 (evidence: [T03-S031])。"
  "**算法评分也算**——美国消费者金融保护局 2024-06 号通函明确：用于招聘、晋升等雇佣决定的**背景档案与算法评分**同样落在 FCRA 的适用范围内，雇主的授权、通知与用途限制义务照旧 (evidence: [T03-S032])。"
  "**犯罪记录不能一刀切**——EEOC 的执法指引要求对逮捕与定罪记录做个案评估（性质、时间、与岗位的关系），而非统一排除 (evidence: [T03-S033])。多州与多市的「公平机会招聘 / ban-the-box」法进一步限制了询问时点 (evidence: [T03-S033])。"
  "**授权链是核心**——背调涉及处理个人信息，须依《个人信息保护法》取得候选人的**单独同意**并明确处理目的、方式、范围与保存期限；委托第三方机构时，委托方与受托方之间也要有相应约定 (evidence: [T03-S034])。**「先做了再补授权」在法律上站不住。**"
  "**红线，如实标注为红线而非技巧**："
  "**合法可做的**：在授权范围内核验学历（学信网）、工作履历（前雇主 HR 确认在职时段与职位）、以及岗位确有必要的资质证书。**薪资流水的调取在中国大陆同样需要单独授权，且很多情况下没有必要性**——如果只是为了定薪锚点，用市场基准比查流水更稳。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "reference-check-walkthrough"
fi
