#!/usr/bin/env bash
# retained.sh — 保留制 retained 的交付流程 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="保留制 retained 的交付流程"

usage() {
  cat <<EOF
retained.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./retained.sh             # interactive
  ./retained.sh --dry-run
  ./retained.sh --json
  ./retained.sh --explain
  ./retained.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "保留制 retained 的交付流程" 工作流。

入门 SOP 共 13 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**阶段一：立项与人选画像（第 0–2 周）**——深度 intake（第 1 条工作流）+ 与关键干系人各自访谈 + 输出**岗位说明书 / position specification**（不是 JD，是一份包含业务背景、成功标准、组织政治现实、挑战与卖点的文档），由客户签字确认。**收第一笔费用**。"
  "**阶段二：市场地图与识别（第 2–5 周）**——按第 3 条工作流画地图；产出 **longlist**。行业公开说法是初始识别可能达到 **100 人甚至更多**，且**约 70% 是被动候选人**（不主动看机会）(evidence: [T03-S051])；也有机构给出 30–80 人的量级 (evidence: [T03-S052])。**这个数字取决于岗位稀缺度与地理范围，引用时必须说明来源与语境。**这一阶段应向客户提交**人才地图本身**作为中期交付物——它的价值独立于是否成单：客户由此知道市场上有谁、他们在哪、大致的薪酬水平、以及为什么某些人不可动。"
  "**阶段三：接触与评估（第 4–8 周）**——按第 4 条工作流触达；对有兴趣者做顾问侧的深度访谈（结构化，按岗位说明书的成功标准）。**收第二笔费用**（通常与呈报名单挂钩）。"
  "**阶段四：呈报 shortlist（第 6–10 周）**——通常 3–6 人。每人一份 **candidate report**。"
  "**阶段五：客户面试与决策（第 8–12 周）**——高管岗位的面试轮次可以很多；有机构直言大型组织的资深高管「有理由预期面对八轮左右的面试，1:1 与小组结合，部分通过电话进行」(evidence: [T03-S051])。顾问在这一段的工作是**双向传话与节奏控制**，不是等消息。"
  "**阶段六：参考人访谈、offer 与入职（第 10–14 周）**——按第 8、9 条工作流；**收尾款**（通常与入职挂钩）。"
  "**阶段七：入职后跟进**——常见做法是入职后 30/90/180 天各回访一次，并把结果写回客户档案。这也是下一单 BD 的自然入口。"
  "**一句话结论**：他为什么值得见（或为什么被列入但有保留）。"
  "**对照成功标准的逐条评估**：把岗位说明书里的每条成功标准列出来，给出证据与判断，**明确写出不满足的那几条**。只写优点的报告没有决策价值。"
  "**职业轨迹摘要**：不是简历复述，是「他在每一段里解决的问题的量级变化」。"
  "**薪酬与动机**：当前结构、期望、**除钱以外的决策要素**、可动性判断与时间窗。"
  "**风险与需要在面试中验证的问题**：给客户 2–3 个具体的追问方向。这一段是顾问专业性最直接的体现。"
  "**顾问的立场**：推荐 / 有保留地推荐 / 供参考。**敢写「有保留」的顾问才有可信度。**"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "retained-walkthrough"
fi
