#!/usr/bin/env bash
# scorecard.sh — 岗位画像与 scorecard SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="岗位画像与 scorecard"

usage() {
  cat <<EOF
scorecard.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./scorecard.sh             # interactive
  ./scorecard.sh --dry-run
  ./scorecard.sh --json
  ./scorecard.sh --explain
  ./scorecard.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "岗位画像与 scorecard" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先写使命，一句话**——说清这个岗位为什么存在，用大白话。Who 方法把 scorecard 拆成三块：**mission（使命）、outcomes（要交付什么）、competencies（怎么干）**，其中 outcomes 是 3–8 条、按重要性排序、可量化 (evidence: [T03-S013, T03-S014])。"
  "**把 JD 从资历清单改写成「前六个月要做成什么」**——具体做法：拿旧 JD 逐条问「这一条是**手段**还是**结果**」。「5 年以上 SaaS 销售经验」是手段，「12 个月内把新签 ARR 从 X 做到 Y」是结果。手段全部降级为「最好有」，结果升级为 outcome。"
  "**补胜任力，但要分两层**——岗位胜任力（为达成这些 outcome 必须表现出的行为）+ 公司文化胜任力（5–8 条，写进每一张 scorecard）(evidence: [T03-S013])。"
  "**合规上游必须是岗位分析**——美国联邦人事管理局（OPM）与《统一雇员选拔程序指南》（UGESP，29 CFR Part 1607）的口径是：选拔标准必须能追溯到对该岗位实际工作内容的分析，而不是凭印象列条件 (evidence: [T03-S010, T03-S015])。**这一条在中国大陆没有对应的强制程序**，但它决定了你的标准在被质疑时能不能自圆其说。"
  "**从 scorecard 反推面试题与评分锚点**——每条 outcome 至少对应一道行为题（「讲一次你……」）或一道情境题（「假设……」），Google re:Work 的做法是给每道题预写**四档答案样例：poor / borderline / solid / outstanding**，让面试官对着锚点打分而不是凭感觉 (evidence: [T03-S002])。OPM 的官方结构化面试指南同样要求预设评分锚点与评分说明 (evidence: [T03-S005])。"
  "**反向检查覆盖矩阵**——画一张「outcome × 面试轮次」的表，确认每条 outcome 至少被两轮独立考到，且没有一条 outcome 被四轮重复考。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "scorecard-walkthrough"
fi
