#!/usr/bin/env bash
# workflow-2.sh — 面试环节设计与面试官校准 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="面试环节设计与面试官校准"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "面试环节设计与面试官校准" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**排几轮**——初筛 1 轮 + 用人经理 1 轮 + 技能/工作样本 1 轮 + 跨部门或高一层 1 轮，共 4 轮是常见量级。Google 公开的做法是核心 loop 4–5 轮，每位面试官提交结构化书面反馈与评分，再由**未见过候选人的资深员工组成的招聘委员会**审阅完整材料后给出录用建议 (evidence: [T03-S006, T03-S023])。Amazon 的 loop 通常 4–5 场、每场 45–60 分钟，通常集中在一天 (evidence: [T03-S007, T03-S024])。"
  "**每轮考什么不重叠**——用第 2 条工作流的「outcome × 轮次」矩阵分配：每轮明确认领 2–3 条，题目从这几条反推。Amazon 的做法就是把领导力准则拆给不同面试官，每人负责一组、并在整个 loop 中评估而不是单设一轮 (evidence: [T03-S024])。"
  "**题目与锚点预写**——每题配四档答案样例（poor / borderline / solid / outstanding），Google 称这样做平均**每场面试节省 40 分钟**，且被拒候选人的满意度比非结构化面试高 35% (evidence: [T03-S002])。行为题（「讲一次你……」）验证过去，情境题（「假设……」）测新场景，两类都要有 (evidence: [T03-S002])。"
  "**面试官培训与准入**——培训内容至少覆盖：怎么按锚点打分、怎么做事实性笔记（记候选人说了什么，不记你的印象）、哪些问题不能问（受保护特征、婚育、薪酬历史）、以及不利影响与工作相关性的基本概念 (evidence: [T03-S015], [T03-S012])。**准入门槛**：新面试官先影随 2 场、再被影随 2 场，才能独立面。"
  "**校准会（每季度 1 小时）**——拿 2–3 份真实的面试记录（去掉结论），让全组各自打分，然后比对分歧。分歧点就是锚点需要改写的地方。校准会的产出应该是**改后的锚点**，不是「大家统一一下认识」。"
  "**debrief 的正确开法（这一步最容易做反）**："
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
