#!/usr/bin/env bash
# workflow-1.sh — 简历筛选与电话初筛 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="简历筛选与电话初筛"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "简历筛选与电话初筛" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**把筛选规则写下来再筛**——列出 3–5 条**淘汰性条件**（工作许可、必备证照、地点、薪酬区间、明确的硬技能门槛），其余一律不作为筛选依据。规则必须能追溯到 scorecard 与岗位分析 (evidence: [T03-S010, T03-S015])。"
  "**该筛什么信号**：与 outcome 直接对应的做过的事（不是待过的地方）、可验证的产出（作品、代码、案例、数字）、职业轨迹里的**变化方向**（在解决越来越难的问题，还是在重复同一件事）、以及硬性淘汰条件。"
  "**不该筛什么**：学历层级与学校名气、公司名气、连续跳槽的表面次数、简历排版与措辞水平。这些不是「政治正确」的建议，而是它们的预测力在数据上就很弱 (evidence: [T03-S021])。**尤其注意**：把学历/年限当门槛还会触发法律风险——美国《统一雇员选拔程序指南》要求任何造成不利影响的选拔工具都要有工作相关性证明，学历门槛是被判过违法的典型 (evidence: [T03-S015])。中国大陆侧，2026 年专项行动明确把「发布含有性别、年龄、地域等不合理限制的歧视性内容」列为纠治对象 (evidence: [T03-S020])。"
  "**用结构化申请表补简历的洞**——在 ATS 里加 3–5 道与 outcome 直接相关的短问答，胜过读第二遍简历 (evidence: [T03-S021])。"
  "**电话初筛脚本（20–30 分钟，固定顺序）**：(a) 2 分钟说清岗位与流程；(b) 5 分钟让候选人讲最近一段经历里他本人做成的一件事，追问「你具体做了什么」而不是「你们团队做了什么」；(c) 5 分钟核对 2–3 条硬条件；(d) 3 分钟问动机与决策要素（为什么现在看机会、下一份工作最看重什么、还在看哪些方向）；(e) 3 分钟对齐时间与薪酬期望——**注意薪酬历史禁问：美国多州禁止询问候选人的薪酬历史，加州 Labor Code 432.3 是最常被引用的一条，并要求应候选人要求提供该岗位的薪酬区间** (evidence: [T03-S012])。合法的问法是问**期望**而不是问**现薪**。(f) 3 分钟留给候选人提问——他问什么，本身就是信号。"
  "**多久一通**——20–30 分钟是主流量级；低于 15 分钟通常问不出「他本人做了什么」，超过 45 分钟等于把用人经理面试提前做了。这是实务惯例，不是有来源的标准。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
