#!/usr/bin/env bash
# workflow-5.sh — 招聘漏斗与数据复盘 SOP walkthrough for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
WORKFLOW="招聘漏斗与数据复盘"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "招聘漏斗与数据复盘" 工作流。

入门 SOP 共 13 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**阶段边界各家不同**——「申请（applied）/ 通过初筛（screened）/ 推荐给用人经理（submitted）」三者的边界在不同 ATS 里不一样。同一支团队换一套系统，比率就会跳变，而流程其实没变 (evidence: [T03-S044])。"
  "**队列错配**——分子（本月拿到 offer 的人）和分母（本月进入流程的人）常常不是同一批人。招聘周期越长失真越大。**正确做法是按进入队列的月份追踪同一批人走完全程**，而不是按自然月横切 (evidence: [T03-S044])。"
  "**time to fill vs time to hire**——起算点不同：前者从职位需求被批准算起，后者从该候选人进入流程算起。争论的实质是「谁背 intake 磨蹭与市场没人的那段空转时间」。更细的三处分歧：终点算 offer accept 还是入职首日；分母只算已填补的岗位（撤销与超期未招到的被剔除，数字被系统性压低）还是包含撤销岗位；用中位数还是平均数 (evidence: [T03-S044])。**看到一个「44 天」之类的基准，先问它是哪个终点、哪个分母、哪种集中趋势。**"
  "**cost per hire 是唯一有正式行业标准的指标**——ANSI/SHRM 06001.2012，公式为「（外部招聘成本合计 + 内部招聘成本合计）÷ 统计期内录用人数」。但即便有标准，各家在内部招聘官薪酬是否分摊、ATS 年费怎么摊、内部转岗算不算一次 hire 这三处仍各行其是，任意一处不同就能差出两三倍 (evidence: [T03-S045])。中文圈的额外坑：很多公司把猎头费记在业务部门预算而非 HR 预算，导致 HR 报出的成本系统性偏低 (evidence: [T03-S045])。"
  "**offer 接受率的分母之争**——口头 offer 算不算？公司撤回的算不算？算到接受还是算到入职？先探口风再发正式 offer 的团队，正式接受率会被推到 95%+，**数字漂亮但没有信息量** (evidence: [T03-S046])。"
  "**source of hire 的归因**——ATS 通常只记最后一次触点，于是「公司官网/直接投递」被系统性高估，品牌曝光与主动寻访被低估。据此砍渠道预算是本行常见的错误决策；更稳的是看**分渠道的分阶段通过率**而不只是最终录用数 (evidence: [T03-S044])。"
  "这个季度关掉的岗位里，多少是以录用收尾、多少是撤销、多少还开着？（对照锚：69.8%）(evidence: [T03-S004])"
  "漏斗哪一层的通过率变化最大？是流程变了还是人群变了？"
  "有没有某个渠道的分阶段通过率显著优于其他？我们给它的投入是不是匹配？"
  "从 debrief 到 offer 的中位天数是多少？这段时间里流失了几个人？"
  "被拒的候选人里，有多少是因为标准、多少是因为薪酬、多少是因为速度？"
  "哪些岗位的 intake 假设已经被数据证伪但还没改？"
  "招聘官的负载可持续吗？（Greenhouse 自己在报告里强调，基准的价值不是对标行业平均，而是判断本团队的负载是否可持续）(evidence: [T03-S004])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
