#!/usr/bin/env bash
# topic-3.sh — 库存 决策助手 for 供应链与生产运营.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="供应链与生产运营"
TOPIC="库存"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 库存 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 同时「库存高」和「缺货」，则这是库存位置问题，不是总量问题。 → 则 案例：成品库压着三个月的滞销规格，同时热销规格天天断货——解法是重设解耦点、把缓冲放到通用半成品层做延迟差异化，而不是把
  • 如果 交期问题的根因是某道工序排不过来，则不要调 MRP 参数。 → 则 MRP 假设产能无限，改提前期、加安全库存、改批量都只是把问题挪到别处。案例：连续三个季度靠拉长标准提前期来「解决」延期

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "同时「库存高」和「缺货」，则这是库存位置问题，不是总量问题。"
  "交期问题的根因是某道工序排不过来，则不要调 MRP 参数。"
)
declare -a RULE_ACTIONS=(
  "案例：成品库压着三个月的滞销规格，同时热销规格天天断货——解法是重设解耦点、把缓冲放到通用半成品层做延迟差异化，而不是把总库存预算再加一成。先做 ABC-XYZ 分类，再谈补货参数"
  "MRP 假设产能无限，改提前期、加安全库存、改批量都只是把问题挪到别处。案例：连续三个季度靠拉长标准提前期来「解决」延期，结果是全公司库存上升、交期照样不准〔T02-S042〕。正解走 TOC 五步：识别瓶颈 → 保护瓶颈 → 其余服从 → 提升瓶颈"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
