#!/usr/bin/env bash
# topic-1.sh — 案例 决策助手 for 供应链与生产运营.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="供应链与生产运营"
TOPIC="案例"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 案例 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 交期长且说不清时间花在哪，则先量在制品与流动时间，不要先要产能。 → 则 利特尔法则给出等式：流动时间 = 在制品 ÷ 产出率。在制品不降，交期不可能降。案例：车间抱怨设备不够、要求买第二台加工
  • 如果 还没定履行模式（MTS / MTO / ATO / ETO），则不要选任何计划系统。 → 则 履行模式决定数据模型，选错是数据模型层面的错配，不是配置能改的。案例：ETO 企业买了 MTS 逻辑的 ERP，每个项目
  • 如果 要压供应商成本，则先用 Kraljic 矩阵分级，再决定用竞价还是共同开发，不要一刀切年降。 → 则 案例：把一个单一来源、技术壁垒高的关键件跟通用标准件用同一个年降比例考核，结果是关键件供应商停止投入改善、质量事故上升，
  • 如果 要给韧性投资排序，则按恢复时间与存活时间排，不按发生概率排。 → 则 案例：Simchi-Levi 方法在汽车行业的经典结论是，最大的风险敞口常常出现在一个采购金额极小、但恢复周期极长的零件

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "交期长且说不清时间花在哪，则先量在制品与流动时间，不要先要产能。"
  "还没定履行模式（MTS / MTO / ATO / ETO），则不要选任何计划系统。"
  "要压供应商成本，则先用 Kraljic 矩阵分级，再决定用竞价还是共同开发，不要一刀切年降。"
  "要给韧性投资排序，则按恢复时间与存活时间排，不按发生概率排。"
)
declare -a RULE_ACTIONS=(
  "利特尔法则给出等式：流动时间 = 在制品 ÷ 产出率。在制品不降，交期不可能降。案例：车间抱怨设备不够、要求买第二台加工中心；画完价值流图发现单件在系统里 18 天、真正被加工不到 4 小时，其余全在等——买设备不解决等待，压投料与批量才解决。工具是价值流图 VSM，不是 APS〔T02-S007〕"
  "履行模式决定数据模型，选错是数据模型层面的错配，不是配置能改的。案例：ETO 企业买了 MTS 逻辑的 ERP，每个项目都要伪装成「标准品 + 大量变更」，三年后系统里的 BOM 没有一份可信〔T02-S042〕"
  "案例：把一个单一来源、技术壁垒高的关键件跟通用标准件用同一个年降比例考核，结果是关键件供应商停止投入改善、质量事故上升，省下的钱远小于停线损失。战略件走长期共生与联合改善，杠杆件才走竞价"
  "案例：Simchi-Levi 方法在汽车行业的经典结论是，最大的风险敞口常常出现在一个采购金额极小、但恢复周期极长的零件上——按采购额或按概率排序，这个零件永远排不进视野〔T01-S036〕"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
