#!/usr/bin/env bash
# topic-2.sh — 准确 决策助手 for 供应链与生产运营.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="供应链与生产运营"
TOPIC="准确"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 准确 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 库存准确率、BOM 准确率、工艺路线准确率没过门槛，则不上 APS。 → 则 APS 会把错误数据变成看起来很专业的错误计划，而且因为界面漂亮，比 Excel 的错误更难被质疑。案例：某厂上线高级排
  • 如果 有人把预测准确率当 KPI 去优化，则先做 FVA（预测增值）判断人工调整到底是加分还是减分。 → 则 预测准确率有天花板，由需求本身的变异度决定；FVA 拿「什么都不做的朴素预测」当基准，看每一道人工干预是提高了还是降低了

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "库存准确率、BOM 准确率、工艺路线准确率没过门槛，则不上 APS。"
  "有人把预测准确率当 KPI 去优化，则先做 FVA（预测增值）判断人工调整到底是加分还是减分。"
)
declare -a RULE_ACTIONS=(
  "APS 会把错误数据变成看起来很专业的错误计划，而且因为界面漂亮，比 Excel 的错误更难被质疑。案例：某厂上线高级排程后计划反而更不可信，根因是工艺路线主数据没人维护、标准工时是五年前的〔T02-S015〕。正确顺序是库存准确率 → BOM 准确率 → 工艺路线 → 再谈 APS"
  "预测准确率有天花板，由需求本身的变异度决定；FVA 拿「什么都不做的朴素预测」当基准，看每一道人工干预是提高了还是降低了准确率。案例：销售部门的月度调整长期让误差变大，去掉这道工序，预测反而更准——这类结果在业内并不罕见，但只有做了 FVA 才能拿出来说话"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
