#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 先定坐标：什么学科、哪一类研究、谁的规则管你
  9.2 这是事前问题还是事后问题
  9.3 现行版本体检
  9.4 证据等级与口径体检
  9.5 合规与诚信坐标
  9.6 工具与可及性体检
  9.7 这次的失败模式是什么

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定坐标：什么学科、哪一类研究、谁的规则管你"
  "这是事前问题还是事后问题"
  "现行版本体检"
  "证据等级与口径体检"
  "合规与诚信坐标"
  "工具与可及性体检"
  "这次的失败模式是什么"
)
declare -a DIM_QUESTIONS=(
  "学科侧（理工 / 生医 / 量化社科 / 定性社科 / 人文）、研究类型（随机试验 / 观察性 / 实验室 / 二手数据 / 系统综述 / 定性）、身份（在读 / 博后 / 独立 PI）、法域（中国大陆 / 其他）、机构（哪所学校、哪个资助方）。"
  "用户此刻站在数据的哪一侧——还没收数据（设计、预注册、伦理、样本量），还是已经有结果（分析、写作、投稿、返修、纠错）。这一条决定了本 skill 能帮上的忙差别极大：事前能提升可信度，事后只能诚实呈现。"
  "涉及的报告规范、法规、期刊政策、资助方要求各自的**现行版本号与生效日期**；有没有「已公布未生效」的情况。"
  "用户带来的每一个数字与结论，分别属于哪一档证据（预注册多中心复制 / 单项自然实验 / 单项相关研究 / 未复制小样本 / 自报），以及它的判据、年份、学科、统计口径。"
  "伦理审查是否触发（中国侧注意人工智能、算法与个人数据处理已被纳入）、个人信息与人类遗传资源是否触发、署名与贡献是否谈定、利益冲突与 AI 使用是否需要披露、有没有踩到明文红线（代写代投、买卖署名、拆分发表、引用操纵）。"
  "机构订阅了什么（引文库版本与回溯年限、学科库、软件授权、系统综述平台、查重名额）；用户所在地的访问限制与替代方案。"
  "这一类任务最常死在哪一步（选题停在主题、检索式不可复现、分析计划含糊、审批没进关键路径、把大修当成快接受了、形式审查被退），以及用户当前离那一步有多远。"
)
declare -a DIM_SOURCES=(
  "\`references/research/03-workflows.md\` 的理工与社科差异表；\`references/research/06-glossary.md\` 的 C 节法规与 J 节速查表；本单位研究生院 / 科研处官网的现行细则。"
  "§1.1 与 §1.2 两个心智模型；\`references/research/03-workflows.md\` 的工作流 3、6。"
  "规范总登记处；出版伦理机构与医学期刊编辑委员会官网；中国侧的科技部 / 教育部 / 基金委官网；\`references/research/06-glossary.md\` 的 B 节与 D 节。"
  "§1.5 与 §2 第 10 条；\`references/research/04-canon.md\` 的论文节、概念节与「数字口径提醒」字段；\`references/research/01-figures.md\` 各词条的口径说明。"
  "\`references/research/06-glossary.md\` 的 C 节；\`references/research/03-workflows.md\` 的工作流 4、12、13；出版伦理机构的场景化流程图。"
  "\`references/research/02-tools.md\` 的选型决策树第 0 问与中国大陆可及性表；本校图书馆网页或学科馆员。"
  "\`references/research/03-workflows.md\` 的总览表「最容易死在哪一步」列；§6 反模式。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "五行坐标表，每行标「已确认 / 待查」。任何一行是「待查」，后面的建议都只能是条件式的。"
  "一句话判定 + 明确告诉用户哪些选项已经关闭（例如「数据已经收完，功效已经定死，事后功效不是补救手段」）。"
  "版本对照表（名称 / 发布方 / 现行版本 / 生效日期 / 你要做什么），并显式标出「本 skill 的信息截止日之后可能已变，需现场核对」。"
  "逐条列「数字 → 判据与口径 → 能支持什么结论 / 不能支持什么结论」。口径缺失的一律改写成定性描述，不要替用户猜。"
  "红黄绿三色清单——红色（明文禁止，立即停）、黄色（需要审批或披露，列出去哪办）、绿色（无约束）。**红线项不给替代方案，只给「不要做」和依据。**"
  "两栏表——「你已经有的」与「你需要的但没有的」，第二栏每项给一个具体替代方案，并说明替代的代价（多数是沟通成本而不是功能）。"
  "指出一个最可能的失败点 + 一个当天就能做完的动作。**不要给十条建议；给一条现在就能执行的。**"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
