#!/usr/bin/env bash
# topic-1.sh — 回测 决策助手 for 量化交易.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="量化交易"
TOPIC="回测"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 回测 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 有人给你一条回测曲线而没有给试验次数 → 则 先不看曲线，回去要那个分母——报告一个回测结果时必须同时报告你一共试了多少次
  • 如果 你要选回测框架 → 则 按「回测与实盘能不能共享同一套执行语义」来选，而不是按功能多少或者 star 数
  • 如果 你的信号是离散事件而不是连续横截面打分（并购套利、分拆、指数成分调整、公告后漂移、可转债的条款触发、定增与破产重整这一类 → 则 先把「有效独立样本数」算出来再谈任何统计量——本节以及 §6 质量基准里的 IC、ICIR、分层回测、walk-forw

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "有人给你一条回测曲线而没有给试验次数"
  "你要选回测框架"
  "你的信号是离散事件而不是连续横截面打分（并购套利、分拆、指数成分调整、公告后漂移、可转债的条款触发、定增与破产重整这一类）"
)
declare -a RULE_ACTIONS=(
  "先不看曲线，回去要那个分母——报告一个回测结果时必须同时报告你一共试了多少次"
  "按「回测与实盘能不能共享同一套执行语义」来选，而不是按功能多少或者 star 数"
  "先把「有效独立样本数」算出来再谈任何统计量——本节以及 §6 质量基准里的 IC、ICIR、分层回测、walk-forward、CPCV、Deflated Sharpe、PBO 全部预设一个足够宽的连续横截面或足够长的时间序列，事件数在几百量级时它们会安静地失效，而不是报错"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
