#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 量化交易.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="量化交易"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 先定坐标：什么市场、什么频率、谁的钱、哪个法域
  9.2 收益来源：这笔钱从谁手里来
  9.3 数据口径体检
  9.4 统计防线：试验次数与留出集
  9.5 成本与容量：净收益还剩什么
  9.6 风险形状：压力下这几条腿会不会一起断
  9.7 中国法域的合规坐标

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定坐标：什么市场、什么频率、谁的钱、哪个法域"
  "收益来源：这笔钱从谁手里来"
  "数据口径体检"
  "统计防线：试验次数与留出集"
  "成本与容量：净收益还剩什么"
  "风险形状：压力下这几条腿会不会一起断"
  "中国法域的合规坐标"
)
declare -a DIM_QUESTIONS=(
  "股票还是期货还是期权；日频以上还是日内；个人自有资金、私募产品还是机构自营；中国法域还是海外。这四项决定了后面每一个维度的答案。"
  "策略的对手方是谁、受什么约束、为什么持续付钱。四类合法答案：风险补偿、行为偏差、制度性约束、提供流动性。"
  "时点性、复权口径、退市与停牌、财报修订、指数成分历史、期货展期规则、期权链完整性。"
  "一共试了多少次、留出集是什么、用过几次、样本外方式与部署方式是否一致、有没有报 Deflated Sharpe 与 PBO。"
  "换手率、四项成本分解、冲击模型形式、容量上限、拥挤度可观测指标。"
  "压力情景下的相关性、杠杆与追保路径、降杠杆规则的历史触发次数、同类策略集中平仓的暴露。"
  "是否触发程序化交易报告义务、每秒与单日申报笔数、撤单频率、四类异常交易、是否可能被认定为高频、私募产品的规模与杠杆自律约束。"
)
declare -a DIM_SOURCES=(
  "直接问用户；用户没说就按最常见组合（中国 A 股 + 中低频 + 有工程能力的个人）默认，并明说这是默认值。"
  "\`references/research/04-canon.md\` 的资产定价与因子文献节；对具体因子先查 Kenneth French 数据库与开放因子复制数据的口径 evidence: [T05-S007, T05-S008]。"
  "\`references/research/02-tools.md\` 第 1 层与避坑清单；中国侧回到数据平台的官方字段文档，海外侧回到 CRSP / Compustat 的口径说明 evidence: [T02-S057, T02-S049]。"
  "\`references/research/03-workflows.md\` 的工作流 6 与跨工作流锚点（Arnott-Harvey-Markowitz 回测协议）evidence: [T04-S068]。"
  "\`references/research/04-canon.md\` 的微观结构与最优执行节（平方根律、Almgren-Chriss、Amihud 非流动性度量）evidence: [T04-S032, T04-S077, T04-S078]。"
  "先看 \`references/research/03-workflows.md\` 的工作流 11、12（可操作的部分在这里），再看 Khandani 与 Lo 对 2007 年 8 月 quant quake 的一手复盘 evidence: [T04-S086]。\`04-canon.md\` 的行业史节可作背景，但**该节自己标注了「叙事材料，不是方法材料」**，其中 LTCM 的数字属百科转述，只能当共同记忆用，不能当方法或数据来源 evidence: [T04-S087]。"
  "证监会与沪深北交易所、期货交易所的规则原文，以及中基协《私募证券投资基金运作指引》（2024-04-30 发布、2024-08-01 施行，**属中基协自律规则而非证监会规章，适用对象只有私募证券基金管理人**——个人系统化交易者不适用）evidence: [T05-S001, T05-S002, T05-S005]；\`references/research/03-workflows.md\` 工作流 13。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句坐标声明——「按 {市场} × {频率} × {资金性质} × {法域} 回答；如果其中任一项不对，结论会变」。"
  "一句话的收益来源假设 + 一句话的失效条件（什么情况下这个来源会消失）。说不出来就明写「未能识别收益来源，按噪音处理」。"
  "一张口径核对表，每项标「已确认 / 未确认 / 不适用」，未确认的项直接列为结论的前提风险。"
  "「试验次数 N = {值或未知}；留出集 = {区间}；已跑 {次数} 次；折价方法 = {DSR / haircut / 无}」。N 未知时，结论一律降一档表述。"
  "按规模档位给出的净收益结论——「在 {规模} 以下净收益为正，超过 {规模} 后由 {成本项} 主导」；数据不足时明写不足。"
  "一段压力叙述——「在 {情景} 下，{这几条腿} 会同时受损，届时杠杆会到 {水平}，事先写好的动作是 {动作}」。"
  "一张阈值卡——「监管线 = {值}；内部线 = {更严的值}；校验位置 = 下单链路前置」，并附一句红线声明：不以成交为目的的申报、自成交、尾市操纵、拆分账户规避报告属于法律问题，不在优化范围内。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
