#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 供应链与生产运营.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="供应链与生产运营"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 先定场景坐标：履行模式与产品结构
  9.2 判断问题属于哪一层：流动、缓冲、约束，还是信号
  9.3 查数字的口径与可信度
  9.4 定位约束与缓冲：谁在付账
  9.5 核对流派前提是否成立
  9.6 查合规与时效变量

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定场景坐标：履行模式与产品结构"
  "判断问题属于哪一层：流动、缓冲、约束，还是信号"
  "查数字的口径与可信度"
  "定位约束与缓冲：谁在付账"
  "核对流派前提是否成立"
  "查合规与时效变量"
)
declare -a DIM_QUESTIONS=(
  "这家是 MTS / MTO / ATO / ETO 哪一种；多级 BOM 有几层、共用件比例；产品生命周期长短与需求变异度。"
  "症状是交期长（流动）、库存高又缺货（缓冲位置）、某工序永远排不过来（约束），还是上游需求剧烈波动（信号放大）。"
  "对方给的交期、库存、准确率各自的口径；数据是系统导出还是现场实测；标准工时上次更新是什么时候。"
  "当前变异被哪种缓冲吸收（库存 / 产能 / 时间）；约束是设备、物料、还是政策；缓冲放在 BOM 哪一层。"
  "要引用的方法（精益拉动、DBR、DDMRP、统计预测）各自的前提条件在这个场景是否满足；有没有更便宜的替代解。"
  "涉及的标准与法规（ISO 9001 / IATF 16949 / APQP-PPAP / Incoterms 2020）版本；2024-2026 的新合规变量（CSDDD、CBAM、涉疆溯源、电池数字护照）是否适用。"
)
declare -a DIM_SOURCES=(
  "\`references/research/02-tools.md\` 第 4 节的五步决策树；\`06-glossary.md\` A7 履行与交付一节的定义。"
  "本文 §1 的七个心智模型；\`03-workflows.md\` 对应工作流的失败模式一节。"
  "企业自己的 ERP 主数据与盘点记录；\`02-tools.md\` 第 4 节第五步的数据体检门槛。"
  "本文 §1.2 与 §1.3；\`03-workflows.md\` 的瓶颈识别与安全库存两条工作流。"
  "\`01-figures.md\` 的谱系速览与十四条互攻；\`04-canon.md\` F 节的五组争议。"
  "\`06-glossary.md\` B 节标准与 B6 合规新变量；发布机构官方页（ascm.org / iso.org / aiag.org / iccwbo.org）。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话锁定「这是一个 {履行模式} + {变异度} 的问题」，并说明这个坐标排除了哪些解法。"
  "先给出层级判定与理由，再给解法。**跳过这一步直接给方案是这行最典型的外行动作。**"
  "列出「已确认口径」与「待确认口径」两栏，待确认项不进结论。"
  "画一句话的「变异 → 缓冲」流向，并指出建议改变的那一处。"
  "明写「本建议基于 {流派}，其前提是 {条件}；若 {条件} 不成立，改用 {替代}」。"
  "列出适用标准与生效时间线，标注 last_checked 与 Decay risk，不确定的明写「需向发布机构核实」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
