#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for 谈判与议价.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="谈判与议价"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果 信息充分（你了解标的、了解市场、了解对方大致处境），则先出价；如果信息明显不对称且你是信息弱的一方，则先问不先报。 → 则 这一条是有条件的，不是铁律：Galinsky 与 Mussweiler 的实验支持先出价的锚定优势，Maaravi 与 
  • 如果 要让步，则一律条件化并标注代价，绝不单方面让步。 → 则 单方让步会被读成「再压一次还会有」；条件化让步（如果你 X，我可以考虑 Y）既保住了节奏，也把让步变成了交换 evide
  • 如果 对方给你一个带截止时间的最终报价，则先确认这个截止是真的还是流程造的。 → 则 爆炸性 offer（限时逼签）是标准施压手法，识别方法是问「如果我需要多两天，会发生什么具体后果」——答不上具体后果的截
  • 如果 谈成了，则当场书面确认，并在离场前清点全部变动项。 → 则 口头共识到书面合同之间有四类固定断点：措辞歧义、过度自信、临门加塞新条件、双方内部激励错位 evidence: [T03
  • 如果 这是跨法域或长期合同，则在起草阶段就选定争议解决条款，不要等谈崩再选。 → 则 仲裁机构、调解程序与执行路径决定了「谈崩要花多少钱、多久」，也就直接决定了你的替代方案值多少钱 evidence: [T
  • 如果 对方的动作触及虚构竞标者、伪造授权、送礼款待或单方录音，则停下来核对法域红线，绝不跟进。 → 则 这些在培训话术里被当技巧，在法律上可能构成欺诈性陈述、商业贿赂或非法取证。中国《反不正当竞争法》2025 年修订（202

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "信息充分（你了解标的、了解市场、了解对方大致处境），则先出价；如果信息明显不对称且你是信息弱的一方，则先问不先报。"
  "要让步，则一律条件化并标注代价，绝不单方面让步。"
  "对方给你一个带截止时间的最终报价，则先确认这个截止是真的还是流程造的。"
  "谈成了，则当场书面确认，并在离场前清点全部变动项。"
  "这是跨法域或长期合同，则在起草阶段就选定争议解决条款，不要等谈崩再选。"
  "对方的动作触及虚构竞标者、伪造授权、送礼款待或单方录音，则停下来核对法域红线，绝不跟进。"
)
declare -a RULE_ACTIONS=(
  "这一条是有条件的，不是铁律：Galinsky 与 Mussweiler 的实验支持先出价的锚定优势，Maaravi 与 Levy 2017 则显示信息不对称时先出价反而吃亏，多议题下先出价还会暴露你的优先级并被自利对手利用 evidence: [T04-S007, T04-S018, T03-S025]"
  "单方让步会被读成「再压一次还会有」；条件化让步（如果你 X，我可以考虑 Y）既保住了节奏，也把让步变成了交换 evidence: [T03-S045, T03-S026]"
  "爆炸性 offer（限时逼签）是标准施压手法，识别方法是问「如果我需要多两天，会发生什么具体后果」——答不上具体后果的截止多半是造出来的 evidence: [T03-S051]。对方说「这是我们的 best and final」时先分场景：在正式招投标程序里它对应联邦采购法规 15.307 的最终方案修订（书面提交、统一截止、之后不再修改），有约束且反悔可能触发废标；**在普通商业谈判里它通常只是一个流程标签，法律上并不构成不可反悔** evidence: [T06-S022, T03-S057]。判据仍然是上面那句：问「如果我需要多两天，会发生什么具体后果」"
  "口头共识到书面合同之间有四类固定断点：措辞歧义、过度自信、临门加塞新条件、双方内部激励错位 evidence: [T03-S059, T03-S055]。防 nibbling（收口后一点点加码）的唯一有效办法是把清单写下来双方确认"
  "仲裁机构、调解程序与执行路径决定了「谈崩要花多少钱、多久」，也就直接决定了你的替代方案值多少钱 evidence: [T03-S062, T03-S067]。中国 2025 年修订的《仲裁法》已于 2026-03-01 施行，既有合同模板需要复核 evidence: [T06-S031, T06-S065]"
  "这些在培训话术里被当技巧，在法律上可能构成欺诈性陈述、商业贿赂或非法取证。中国《反不正当竞争法》2025 年修订（2025-10-15 施行）后商业贿赂条款移到**第八条**（旧法在第七条，**新法第七条改为混淆行为**，引用旧序号是常见错误），罚则在第二十四条 evidence: [T06-S006, T06-S074, T03-S038]；美国录音是一方同意还是全体同意按州而不同 evidence: [T03-S034, T03-S035]；中国的个人信息处理走告知—同意规则 evidence: [T03-S023, T06-S017]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
