#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 先定坐标：谁在问、站哪一侧、什么岗位
  9.2 分清这是判断问题、供给问题，还是说服问题
  9.3 回到 intake：需求本身是不是可证伪的
  9.4 核对数字的口径、样本与来源等级
  9.5 查合规坐标：法域、工具、时效
  9.6 核对流派前提是否成立
  9.7 算一遍账：漏斗、时间与激励

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定坐标：谁在问、站哪一侧、什么岗位"
  "分清这是判断问题、供给问题，还是说服问题"
  "回到 intake：需求本身是不是可证伪的"
  "核对数字的口径、样本与来源等级"
  "查合规坐标：法域、工具、时效"
  "核对流派前提是否成立"
  "算一遍账：漏斗、时间与激励"
)
declare -a DIM_QUESTIONS=(
  "提问者是甲方招聘、用人经理，还是猎头顾问；岗位是量大标准化、稀缺技能、还是高管寻访；地域是中文市场还是英文市场；这是新增岗位还是替换。"
  "症状是「找不到人」（供给）、「面了很多定不下来」（判断）、还是「谈到最后跑了」（说服）。三者的解法完全不同，用错解法是本行最常见的浪费。"
  "成功标准有没有写成「前九十天要做成的三件事」；「必须有 vs 最好有」有没有排序；薪酬区间与市场基准差多少；用人经理本人到没到场。"
  "每个被引用的比例与天数——起算点是哪天、分母是什么、样本来自哪里、是同行评审还是厂商自有。"
  "涉及自动打分/排序/视频面试的，落在哪几部规则下（纽约市、伊利诺伊、加州、欧盟、中国）；涉及背调与个人信息的，授权链是否完整；涉及薪酬与提问边界的，该法域是否禁止询问薪酬历史。"
  "要引用的方法（结构化面试、Topgrading 履历深挖、潜力评估、A player 论、直聊式效率优先）各自的前提在这个场景是否满足；有没有更便宜的替代解。"
  "从要几个入职倒推需要多少触达；这个周期里用人经理能给多少反馈时间；提出建议的人（含你自己）怎么收钱、这个激励会把建议往哪边推。"
)
declare -a DIM_SOURCES=(
  "本文 §1 的七个模型作分诊表；\`references/research/02-tools.md\` 的选型决策树给出甲乙方分岔。"
  "本文 §1.1 与 §1.5；\`references/research/03-workflows.md\` 的漏斗复盘一节给出按层定位的方法。"
  "本文 §1.4 与 §4 的 intake 一节；\`references/research/03-workflows.md\` 的必问问题清单可直接抄。"
  "\`references/research/06-glossary.md\` 的度量口径一节；\`references/research/04-canon.md\` 的来源等级对照表。"
  "\`references/research/06-glossary.md\` C 节法规原文与 E 节时效变化；官方发布口（\`eeoc.gov\` / \`ecfr.gov\` / \`eur-lex.europa.eu\` / \`gov.cn\` / \`mohrss.gov.cn\`）。"
  "本文 §7 的六派对照；\`references/research/04-canon.md\` 的分歧节；\`references/research/01-figures.md\` 的公开对立关系表。"
  "本文 §1.5 与 §1.6；\`references/research/03-workflows.md\` 的漏斗算法与猎头侧接单一节。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话锁定「这是一个 {哪一侧} + {哪类岗位} + {哪个市场} 的问题」，并说明这个坐标排除了哪些解法。"
  "先给出判定与依据（落在漏斗哪一层），再给解法。**跳过这一步直接给方案，是这行最典型的外行动作。**"
  "把对方给的需求逐条标注「可证伪 / 形容词」，形容词条目退回重写；少于三条可证伪就明说这个岗位还不该开。"
  "列「可用数字」与「需回查数字」两栏，需回查项不进结论；引用效度数值时注明是哪一版元分析。"
  "列出适用规则与生效时间线，标注 \`last_checked\` 与 \`Decay risk\`，不确定的明写「需回查官方原文」；**不提供任何规避路径**。"
  "明写「本建议基于 {流派}，其前提是 {条件}；若 {条件} 不成立，改用 {替代}」。"
  "给出触达量与时间的估算区间并标明假设，再明写「我的激励结构是 {什么}，它可能让这条建议偏向 {哪边}」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
