#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 形态与「能不能不用机器人」
  9.2 精度口径与误差预算
  9.3 性能声明的分母还原
  9.4 数据路线与许可证
  9.5 仿真可信度与 sim-to-real 归因
  9.6 安全合规与法域时效
  9.7 工具版本与生命周期

背后的心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。
  • 难建模的用数据补，可建模的别用数据学: 模型与数据不是替代关系是分工关系，分工线画在「这一段物理量可不可辨识」上——驱动器的非线性与迟滞难写、用数据拟合；刚体动力学、约束与几何写得出来、就别浪费样本去学。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "形态与「能不能不用机器人」"
  "精度口径与误差预算"
  "性能声明的分母还原"
  "数据路线与许可证"
  "仿真可信度与 sim-to-real 归因"
  "安全合规与法域时效"
  "工具版本与生命周期"
)
declare -a DIM_QUESTIONS=(
  "任务的容差、节拍、来料变异范围、运行模式清单；以及三个替代方案的成本——改工装 / 改来料呈现、专机或桁架、维持人工工位。"
  "对方给的精度是重复定位精度还是绝对精度、按什么标准在什么负载与速度下测的；末端所需精度能否由相对定位（视觉或力控二次找正）承担。"
  "任何成功率、自主率、泛化数字的六个字段——任务数 × 试验次数、真机还是仿真、是否新物体新场景、有无人工接管或重试、判定标准、谁验证的。"
  "这个任务该走遥操作、手持采集、仿真合成还是边干活边采；候选数据集与模型权重的许可证是否允许商用。"
  "这套仿真服务于训练、验节拍还是数字孪生；差距主因是参数不确定（可用域随机化）还是结构性缺失（接触、柔性、延迟、线缆，必须真机）。"
  "交付法域（欧盟 / 美国 / 中国）、适用标准与其版本、生效日与适用日的差别、是否需要公告机构或第三方；以及这个应用是不是协作应用。"
  "候选工具的最后一次 commit、最近一个 release、有没有 EOL 公告、许可证、以及它属于必备 / 场景特化 / 新兴的哪一层。"
)
declare -a DIM_SOURCES=(
  "\`references/research/03-workflows.md\` 工作流 1 与 2；集成商公开的部署手册与验收规范；招聘 JD 里的工位描述反推分工。"
  "\`references/research/06-glossary.md\` **G 节**（评测与运营指标，accuracy / repeatability / 循环时间 / 节拍 / 干预率的口径）与 **I 节**（ISO 9283 / GB/T 12642 的测法与适用条件）；A 节是本体与机械术语（负载、重心、可反驱）。厂商官方技术文档而非彩页。"
  "论文的实验节而不是摘要；\`references/research/01-figures.md\` §3.2 的时间表分歧表（按利益关系分组）；\`05-sources.md\` 的数据集节（一条「轨迹」在不同数据集里不是同一回事）。"
  "\`references/research/05-sources.md\` 第五节（数据集与 benchmark，含规模口径与许可证）；\`02-tools.md\` 的许可证列；数据集与模型仓库的 LICENSE 原文，不看 GitHub 标签。"
  "\`references/research/02-tools.md\` 仿真器条目的接触求解器差异；\`04-canon.md\` 概念 13 与域随机化条目；\`03-workflows.md\` 工作流 8。"
  "\`references/research/06-glossary.md\` I–N 节（每条带版本、发布日、适用日、法域、适用对象）与其 12–24 个月时效风险表；标准发布机构官网与政府法规原文。"
  "\`references/research/02-tools.md\` 三层表与「近 12 个月工具栈的真实变化」表；项目官方 release 页与 EOL 公告，不看第三方榜单。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句「推荐形态 + 被否形态与理由」，外加一行「不上机器人的替代方案成本量级」。"
  "一张三行的误差预算判断——「所需末端精度 / 本体能提供的口径 / 缺口由谁补」。"
  "「还原后的口径 + 这个数字能支持什么结论、不能支持什么结论」两句。"
  "「推荐路线 + 成本量级 + 许可证结论（可商用 / 不可商用 / 需换实现）」。"
  "「仿真在本任务上的可信区与不可信区 + 归因结论 + 下一步是留在仿真还是转真机」。"
  "「适用标准清单（带版本与适用日）+ 本项目的合规路径 + 时效风险点」。**任何绕过风险评估或屏蔽安全功能的做法一律拒绝并说明理由。**"
  "「推荐版本组合 + 每个选择的代价 + 三个月后需要复查的项」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
