#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 广告外包公司绩效管理.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="广告外包公司绩效管理"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 定位/定价与考核口径判定
  9.2 人效基线核算（LUBRM）
  9.3 分岗位指标设计
  9.4 激励与分配设计
  9.5 考核执行与反绩效主义防坑
  9.6 乙方风险与 AIGC 调优

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "定位/定价与考核口径判定"
  "人效基线核算（LUBRM）"
  "分岗位指标设计"
  "激励与分配设计"
  "考核执行与反绩效主义防坑"
  "乙方风险与 AIGC 调优"
)
declare -a DIM_QUESTIONS=(
  "agency 怎么定价(工时制/项目制/retainer/价值制)、定位与客户结构——决定考核口径。"
  "utilization/realization/项目利润率/人均毛利/AGI per head 现状。"
  "各岗可量化性(创意三层/媒介硬指标/AE 客户/BD 销售)。"
  "提成 vs 固定+奖金 vs 项目分成 vs 合伙人；获取分享+熔断是否适用。"
  "PBC/OKR 闭环、校准、强制分布用不用、指标会不会被刷(Goodhart)、是否杀创意。"
  "甲方不确定性(改稿/账期/比稿)如何纳入+合同前置对冲；AIGC 对工时制的冲击。"
)
declare -a DIM_SOURCES=(
  "Track 04 定价 canon(Enns/Williams) + Track 03 阶段 0。"
  "PSA/工时数据(Track 02) + LUBRM 框架(Track 01 Maister/Track 06)。"
  "Track 03 分岗位 SOP + Track 04 创意可量化三层。"
  "Track 01(华为/稻盛/Williams) + Track 03 阶段 4。"
  "Track 03 阶段 5-6 + Track 01(Deming/Muller/索尼)。"
  "Track 01(Enns/Farmer) + Track 02(计费工时悖论) + Track 03。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "定价方式 + 对应考核口径(util vs 项目毛利 vs 客户价值)。"
  "人效四件套数值 + 诊断(问题在人还是在定价)。"
  "每岗指标(质量软评/效率结果硬指标)+权重，标哪层靠评议。"
  "分配机制 + 奖金池核算方式 + 协作/个人平衡 + 创意非物质激励。"
  "考核流程(目标→述职→校准→面谈→应用) + Goodhart 复审点 + 强制分布适用层级。"
  "甲方风险纳入指标+合同对冲方案 + AIGC 后考核口径调整(转单位价值)。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
