#!/usr/bin/env bash
# sim-to-real.sh — sim-to-real 迁移与真机调试 SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="sim-to-real 迁移与真机调试"

usage() {
  cat <<EOF
sim-to-real.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sim-to-real.sh             # interactive
  ./sim-to-real.sh --dry-run
  ./sim-to-real.sh --json
  ./sim-to-real.sh --explain
  ./sim-to-real.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "sim-to-real 迁移与真机调试" 工作流。

一句话: 从「仿真里能跑」到「真机上能跑」，并且知道**什么时候该停止折腾仿真、直接上真机**。

入门 SOP 共 6 步, 失败模式自检 5 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先对齐再随机化**（角色：控制工程师）。做最小系统辨识（关节摩擦阻尼、执行器延迟与力矩上限、传动柔性），把随机化的中心放在辨识值上。腿足领域的标准做法是训练 actuator network：用真机部署时记录的关节数据训练一个 MLP，使其输出的力矩与真实关节位置/速度下的力矩误差最小。evidence: [T03-S043, T04-S055]"
  "**配域随机化**（角色：算法工程师）。原则是**覆盖真机实际会遇到的范围**，不是越大越好——官方文档明确指出随机化范围越大策略越难学，但能容纳更大的输入与系统参数变化。evidence: [T03-S040, T03-S043]"
  "**观测与时序对齐**（角色：软件工程师）。相机帧率、控制频率、通信延迟、动作执行延迟必须在仿真里建模。UMI 明确处理了这一类问题：手持采集时观测与动作**没有**延迟，而推理时存在传感、推理、执行三类延迟，因此策略接口里要做推理时延迟匹配，并用相对轨迹动作表示。evidence: [T03-S013]"
  "**先跑受限真机测试**（角色：控制 + 安全）：降速、限力、限工作空间、人手放在急停上。"
  "**量化 gap 并归因**（角色：算法负责人）：在一致性测点上比仿真与真机（见工作流 5 第 6 步的「一致性测点」），把差异归到「动力学 / 感知 / 时序 / 接触」四类之一。"
  "**决定是继续调仿真还是转真机**（角色：算法负责人）→ 见下面的判据。"
)
declare -a FAILURE_MODES=(
  "**报仿真成功率当结论**（本行第十号破绽）。破解：真机 N 次里成功多少、sim2real 掉了多少，两个数字都要给。evidence: [T06-S044]"
  "**随机化范围一把开到最大**：策略学到极度保守的行为，节拍完全不达标。evidence: [T03-S040]"
  "**忽略延迟**：把时序问题误诊为策略能力问题，然后去加数据。evidence: [T03-S013]"
  "**观测里混进特权信息**：仿真无敌、真机瞎跑。evidence: [T04-S057]"
  "**第一次真机不降速**：撞机损失几天到几周。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sim-to-real-walkthrough"
fi
