#!/usr/bin/env bash
# workflow-12.sh — 监控、失败复盘与迭代 SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="监控、失败复盘与迭代"

usage() {
  cat <<EOF
workflow-12.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-12.sh             # interactive
  ./workflow-12.sh --dry-run
  ./workflow-12.sh --json
  ./workflow-12.sh --explain
  ./workflow-12.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "监控、失败复盘与迭代" 工作流。

一句话: 从「上线之后」到「每一次失败都能被复现、被归类、被转成一个明确的下一步动作」——并且知道**什么时候该重新采数据、什么时候只是调参、什么时候该改硬件**。

入门 SOP 共 7 步, 失败模式自检 5 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先定要监控的指标基线**（角色：项目/运维）。至少：循环时间、干预次数与干预率、失败分类计数、直通率/良率、可用率或 OEE、以及**自主完成 vs 有人兜底**的比例。evidence: [T06-S044]"
  "**上线日志与回放**（角色：软件工程师）。机器人侧滚动录制短片段（分钟级）并自动上传，云端按时间线合并多源数据回放。工具侧的常见做法是设备上记录 MCAP/rosbag 片段、由 agent 自动上传，之后用同一套布局在同一时间线上回放多文件、多传感器、多机器人。evidence: [T03-S048, T03-S049]"
  "**建失败分类学**（角色：算法/项目负责人）。建议的一级分类：感知错 / 定位标定漂移 / 规划或轨迹问题 / 控制与力控问题 / 抓取与工装问题 / 上下游与来料问题 / 硬件故障 / 场景超出设计范围 / 人为操作问题。"
  "**每次失败强制归类并留证据**（角色：现场 + 工程）。归类要有对应的日志片段/视频/图片。"
  "**按分布决定下一步**（角色：技术负责人）→ 见下面的信号规则。"
  "**改动后做 A/B 回归**（角色：评测负责人）。用工作流 9 的协议做配对比较，不要用「感觉好多了」。evidence: [T03-S002, T03-S009]"
  "**把新失败案例回灌到评测集与数据集**（角色：数据负责人）。"
)
declare -a FAILURE_MODES=(
  "**只存汇总指标不存原始数据**：知道变差了，不知道为什么。破解：滚动录制 + 自动上传。evidence: [T03-S048]"
  "**所有失败都归因为「模型能力不足」**：于是无限加数据。破解：强制分类。"
  "**干预不记账**：现场工人顺手扶一把、重摆一下，从不记录，导致「成功率」虚高。破解：把干预做成必须记录的动作。evidence: [T06-S044]"
  "**改动不做回归**：几轮之后无人知道当前版本比三个月前好还是差。evidence: [T03-S002]"
  "**日志只在开发机上有**：现场设备为省磁盘关掉了录制。破解：分片滚动 + 保留策略。evidence: [T03-S048]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-12-walkthrough"
fi
