#!/usr/bin/env bash
# workflow-5.sh — 仿真环境与资产准备（建模到什么程度就够） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="仿真环境与资产准备（建模到什么程度就够）"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "仿真环境与资产准备（建模到什么程度就够）" 工作流。

一句话: 从「CAD 与真机」到「一个能跑、能并行、且在**你关心的那几个量**上与真机对得上的仿真环境」——同时明确列出哪些东西仿真里永远不要信。

入门 SOP 共 6 步, 失败模式自检 5 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**明确仿真要回答什么问题**（角色：算法负责人）。三类目的完全不同：①训练策略（要快、要能并行、接触保真度重要）②验证节拍与可达性（要几何准确，物理可以粗）③做数字孪生（要与真机数据同步，照 CAD 建的静态仿真不算数字孪生）。evidence: [T06-S044]"
  "**准备机器人模型**（角色：仿真工程师）。URDF/MJCF → USD 的转换在 Isaac Lab 有官方转换器；导入时要处理惯量张量、质量、关节驱动增益、碰撞几何。evidence: [T03-S046, T03-S047]"
  "**做碰撞体简化**（角色：仿真工程师）。视觉网格可以高面数，碰撞网格必须简化：凸包、包围盒、基本体，或用凸分解（VHACD / CoACD）得到多个凸块。直接拿视觉网格做碰撞既慢又容易不稳。evidence: [T03-S085, T03-S084, T03-S086]"
  "**配传感器与观测**（角色：仿真工程师）。相机内参、噪声、帧率、延迟要与真机一致；观测里不要塞真机拿不到的特权信息（除非明确走 teacher-student 特权学习路线）。evidence: [T06-S044, T04-S057]"
  "**做最小系统辨识**（角色：控制工程师）。至少辨识：关节摩擦/阻尼、执行器延迟与力矩上限、传动柔性。腿足领域的通行做法是训练一个 actuator network 来拟合真实执行器的非线性响应（把真机记录的关节数据拿去拟合 MLP）。evidence: [T03-S043, T04-S055]"
  "**写「仿真不可信清单」**（角色：算法负责人）。典型条目：摩擦系数与接触刚度、软体与线缆、抓取时的滑移、相机在真实光照与反光下的表现、电机热衰减、连接器/线束干涉。"
)
declare -a FAILURE_MODES=(
  "**建模精度往「像不像」上使劲，而不是往「接触对不对」上使劲**：渲染很漂亮，接触参数没辨识过。"
  "**用视觉网格当碰撞体**：并行数上不去，训练慢十倍。evidence: [T03-S085, T03-S084]"
  "**仿真里能拿到真值位姿**：策略学会依赖真值，真机没有。"
  "**报仿真成功率当能力证据**（本行第十号破绽）：内行只会问真机 N 次里成功多少、sim2real 掉了多少。evidence: [T06-S044]"
  "**把离线编程仿真叫「数字孪生」**：中文产业语境里这个词已被泛用到失去含义。evidence: [T06-S044]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
