#!/usr/bin/env bash
# workflow-10.sh — 安全评估与合规 SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="安全评估与合规"

usage() {
  cat <<EOF
workflow-10.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-10.sh             # interactive
  ./workflow-10.sh --dry-run
  ./workflow-10.sh --json
  ./workflow-10.sh --explain
  ./workflow-10.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "安全评估与合规" 工作流。

一句话: 从「一个能干活的机器人单元」到「一份能过审、能签字、能在事故后站得住的安全文件包」。

入门 SOP 共 8 步, 失败模式自检 6 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**确定机械限制**（角色：安全工程师 + 方案）。机型、负载、末端与工具、工件、循环时间、**全部运行模式**（正常 / 设置示教 / 卡料恢复 / 维护 / 可预见误用）与人员类别。evidence: [T06-S007, T03-S023]"
  "**识别危险**（角色：安全工程师）。挤压、剪切、冲击、工具（刀具/焊枪/激光）、工件（尖锐/高温/掉落）、电气、热、噪声、以及**人机同时在场**的场景。"
  "**风险评估（估计 + 评价）**（角色：安全工程师）。按严重度 / 暴露频次 / 发生概率 / 可避免性打分。**同一份 15066 的不同解读会导致不同的风险评估结论，学术界已有专门研究指出这一点**——所以解读口径要写进报告。evidence: [T03-S029, T06-S007]"
  "**按三步法减小风险**（角色：安全工程师 + 设计）：①本质安全设计（改机构、降速度、降力、去尖角、改布局）→ ②安全防护与补充措施（围栏、光幕、安全扫描仪、安全限速/限位、双手控制、使能装置）→ ③使用信息（说明书、标识、培训）。**顺序不能颠倒。**"
  "**定义安全功能并做 PL/SIL 计算**（角色：功能安全工程师）。**PL/SIL 是安全功能的属性，不是整机属性**——写法是「急停功能达 PLd Cat.3」「安全限速功能达 PLd」。evidence: [T06-S044, T06-S008, T06-S018]"
  "**实测验证**（角色：安全工程师 + 第三方设备）。"
  "**验证与确认（V&V）并留档**（角色：安全工程师 + 质量）。逐条检查每个安全功能是否按设计实现、是否可被旁路、失效模式如何。ISO 13849 / IEC 62061 / IEC 61508 都要求对安全系统做验证。evidence: [T03-S026, T06-S008, T06-S018]"
  "**出地区合规文件**（角色：合规负责人）。"
)
declare -a FAILURE_MODES=(
  "**「协作机器人天生安全，不用围栏」**（本行第五号破绽）：协作是应用属性；装上刀具就不再是协作应用。evidence: [T06-S044, T03-S023]"
  "**「15066 认证」**：TS 不可认证，且内容已并入 ISO 10218:2025。evidence: [T06-S044, T06-S026]"
  "**「我们有 CE 认证」**：CE 是自我声明。evidence: [T06-S044]"
  "**「这台机器人是 PLd 的」**：PL 属于安全功能不属于整机。evidence: [T06-S044]"
  "**把安全留到最后一周**：撞上出货节点，于是有人提议「先把光幕短接过了这一批」——这就是红线。evidence: [T06-S044]"
  "**只算不测**：停止距离与接触力必须实测。evidence: [T03-S026]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-10-walkthrough"
fi
