#!/usr/bin/env bash
# workflow-1.sh — 任务定义与可行性判断（先证明「不该上机器人」） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="任务定义与可行性判断（先证明「不该上机器人」）"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "任务定义与可行性判断（先证明「不该上机器人」）" 工作流。

一句话: 从「客户/老板说想上机器人」到「一份写明该不该做、做哪一段、按什么指标验收的任务书」。**这一步的主要产出经常是「不做」或「先不做机器人」。**

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**去现场，掐表，拍视频**（角色：方案工程师 + 现场班组长）。输入：工位实况；输出：一段完整循环的视频 + 手工分解的动作时间表。"
  "**先问三个「能不能不上机器人」**（角色：方案工程师 + 客户工艺）。①能不能改工装/夹具/送料方式，让人做得更快更稳？②能不能改产品设计或来料状态（定向包装、托盘化、增加定位特征）？③能不能改流程顺序或合并工位？输出：三条替代方案的成本与工期，与机器人方案并列。"
  "**量化来料变异**（角色：工艺 + 质量）。输出：位置/姿态/尺寸/表面状态的分布（不是「大概」，是抽样测出来的范围与离群比例）。"
  "**写全部运行模式，不只写正常模式**（角色：方案工程师 + 安全工程师）。ISO 12100 的「确定机械限制」这一步要求把设置、卡料恢复、维护、可预见误用都算进去。evidence: [T06-S007, T03-S023]"
  "**算一笔含全成本的账**（角色：销售/项目经理 + 客户财务）。分母要含：本体 + 末端工装 + 视觉 + 安全件 + 电控 + 集成人工 + 停线改造 + 培训 + 备件与运维。本行的常识是**本体常只占项目总价的 20–40%**。evidence: [T06-S013]"
  "**定验收指标与测法，写进任务书**（角色：项目经理 + 客户）。每条指标必须写：定义、测法、样本量、判定标准、谁签字。evidence: [T03-S060, T03-S061]"
)
declare -a FAILURE_MODES=(
  "**拿演示视频当可行性依据**：客户看了某厂商发布会就要求「这个我们也做」。破解：要求对方给分母（多少次、什么初始分布、有没有人接管）。evidence: [T06-S044]"
  "**把「柔性」写进需求却不定义换型时间**：结果方案按最难的产品设计，成本翻倍。破解：让客户排出产品族与切换频率，定义换型时间上限。evidence: [T06-S044]"
  "**需求里只有正常模式**：异常恢复到调试期才发现要占 30% 的工程量（本轨未获取该比例的公开一手数据，此处只写「常被严重低估」）。"
  "**用本体单价谈判**：签完才发现工装与视觉预算不够。evidence: [T06-S044]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
