#!/usr/bin/env bash
# workflow-9.sh — 评测协议设计与「怎么读别人的评测」 SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="评测协议设计与「怎么读别人的评测」"

usage() {
  cat <<EOF
workflow-9.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-9.sh             # interactive
  ./workflow-9.sh --dry-run
  ./workflow-9.sh --json
  ./workflow-9.sh --explain
  ./workflow-9.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "评测协议设计与「怎么读别人的评测」" 工作流。

一句话: 从「感觉它变好了」到「一份别人能复现、能反驳、带不确定度的结论」。**这是本行最能区分专业与业余的一步，也是最大的一笔糊涂账所在。**

入门 SOP 共 8 步, 失败模式自检 7 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定任务集与判定标准**（角色：评测负责人）。每个任务写清「成功=什么」（例如：完整放入托盘且未倾倒），二值判定要能由不知情的第三人复判。"
  "**定初始状态随机化范围并写下来**（角色：评测负责人）。例如「物体位置在 30×30 cm 内均匀随机，姿态随机 ±180°，光照两档」。"
  "**定试验次数并预先声明**（角色：评测负责人）。真机评测的现实约束是样本量小：公开研究指出策略比较的可行样本量常在**10 或 50 的量级**，操作研究中**典型只做 20–30 次真机试验**。evidence: [T03-S002]"
  "**定干预记法——这一条最重要**（角色：评测负责人）。必须把下面几类分开记："
  "**做盲测与配对比较**（角色：评测负责人）。TRI 在 LBM 研究中的做法是引入统计评测框架，在仿真与真机上都做**盲 A/B 测试**；同一份工作里做了约 **1,800 次真机 rollout** 与 **47,000+ 次仿真 rollout**。evidence: [T03-S010, T03-S011]"
  "**算不确定度，不只报点估计**（角色：评测负责人）。小样本二项比例要给置信区间；比较两个策略要用能控制错误率的方法。近期方法学工作提供了**序贯/随时有效的检验**（安全随时有效推断 SAVI），允许在证据积累够时提前停止，同时保持预先设定的置信水平。evidence: [T03-S002, T03-S008]"
  "**记录环境与硬件配置**（角色：评测负责人）。硬件型号、相机位置、光照、物体清单、软件版本、标定日期都要记，且**评测环境要可重建**。硬件供应商侧的建议同样是：控制该控制的变量、记录硬件与传感器配置、逐次记录试验。evidence: [T03-S076]"
  "**公开逐次记录**（角色：评测负责人）。不是只给汇总成功率，要给每次的结果与失败原因分类。"
)
declare -a FAILURE_MODES=(
  "**无分母成功率**（本行第二号破绽）。evidence: [T06-S044]"
  "**看着好就停**：optional stopping 使 p 值失效。破解：预先声明 N，或用随时有效的序贯方法。evidence: [T03-S002, T03-S008]"
  "**把接管后的成功计入自主成功**：本行最大的糊涂账。破解：三分类记法（自主成功 / 介入后成功 / 失败）。evidence: [T06-S044]"
  "**拿仿真成功率当能力证据**。evidence: [T06-S044]"
  "**只报二元成功率**：忽略了完成时间、恢复行为、失败严重度等信息；近期方法学工作正是针对「超越二元成功率」的度量做的。evidence: [T03-S008]"
  "**评测集与训练集在场景/物体上重叠**：泛化被高估。"
  "**自家人非盲评**。破解：盲 A/B。evidence: [T03-S010]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-9-walkthrough"
fi
