#!/usr/bin/env bash
# workflow-11.sh — 现场部署与集成（节拍、换型、异常恢复、PLC/MES 边界） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="现场部署与集成（节拍、换型、异常恢复、PLC/MES 边界）"

usage() {
  cat <<EOF
workflow-11.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-11.sh             # interactive
  ./workflow-11.sh --dry-run
  ./workflow-11.sh --json
  ./workflow-11.sh --explain
  ./workflow-11.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "现场部署与集成（节拍、换型、异常恢复、PLC/MES 边界）" 工作流。

一句话: 从「实验室里能跑的单元」到「在客户产线上按节拍连续生产、能换型、能自己从异常里爬出来」的设备。

入门 SOP 共 8 步, 失败模式自检 6 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**厂内预验收 FAT**（角色：集成商项目经理 + 客户工程）。在集成商现场、用客户的真实零件、按书面规格逐条验证。FAT 是发运前的第一次正式验证，在电柜制作、软件配置、机械装配与内部质检完成之后进行。evidence: [T03-S062, T03-S060]"
  "**发运、就位、接电接气接网**（角色：安装队 + 客户设施）。"
  "**现场标定与首件验证**（角色：调试工程师）→ 复用工作流 4；此时坐标系要与客户产线基准对齐。"
  "**接上位系统：定清楚边界**（角色：控制工程师 + 客户 IT/自动化）。"
  "**节拍调试**（角色：调试工程师）。测**循环时间**并与客户**节拍**比较，留余量。**节拍是需求侧配额，循环时间是实际耗时，两者不能混用。** evidence: [T06-S044]"
  "**异常恢复设计与演练**（角色：调试 + 客户操作工）。对每一类异常（没看到、抓空、掉件、卡料、超力、超时、上游断料、下游堵塞）演练恢复流程，并写进手册。"
  "**换型验证**（角色：调试 + 客户工艺）。实测从上一产品切到下一产品的**换型时间**（含换爪、改程序、重标定、首件验证），并确认操作工能独立完成。evidence: [T06-S044]"
  "**SAT 现场验收 + 培训 + 移交**（角色：项目经理 + 客户）。SAT 在真实运行环境下、用客户零件、客户操作工、产线接口与维护流程一起验证；通过 SAT、完成培训、交付移交包、遗留问题正式约定，项目才算完成。evidence: [T03-S060, T03-S061]"
)
declare -a FAILURE_MODES=(
  "**来料在现场比样品差**：厂内用挑过的好件做 FAT，现场用真实来料就崩。破解：FAT 必须用客户提供的**真实批次**件，含边界件。evidence: [T03-S062]"
  "**安全信号接进普通 IO**：审查不过，且事故时无免责空间。evidence: [T03-S067]"
  "**验收只做单次成功不做连续运行**：验收当天好，第二周不行。破解：验收含连续运行与干预率。evidence: [T06-S044]"
  "**换型没人会**：设备变成「只做一种产品的专机」。evidence: [T06-S044]"
  "**把「免编程/零代码」当成不需要工程师**：图形化示教覆盖标准工序，异常处理、节拍优化与换型仍要工程师。evidence: [T06-S044]"
  "**本体 MTBF 当系统可用率依据**。evidence: [T06-S044]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-11-walkthrough"
fi
