#!/usr/bin/env bash
# workflow-7.sh — 数据采集与训练循环（遥操作的人力成本与停止条件） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="数据采集与训练循环（遥操作的人力成本与停止条件）"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "数据采集与训练循环（遥操作的人力成本与停止条件）" 工作流。

一句话: 从「决定走学习路线」到「一批可训练、可复现、知道自己缺什么的数据 + 一条能持续迭代的训练循环」，并且知道**什么时候该停止采数据**。

入门 SOP 共 7 步, 失败模式自检 5 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先冻结采集协议再采第一条**（角色：数据负责人）。DROID 的做法是用一份共享采集协议来统一 13 个机构、50 名采集员、18 套完全相同的硬件（Franka Panda + Robotiq 2F-85 + 两台桌面 ZED 2 + 一台腕部 ZED Mini），协议专门用来防止「相机看不见机器人」「采集员入镜」这类常见错误。evidence: [T03-S012, T03-S077]"
  "**先采 20–50 条做贯通测试**（角色：数据负责人 + 算法）。走完「采集 → 转格式 → 训练 → 部署 → 真机跑一次」的完整链路。"
  "**按「变化维度 × 每维重复次数」排采集计划**（角色：数据负责人）。LeRobot 官方给 SmolVLA 的起步建议是**约 50 条 episode**，示例是 **5 个不同物体位置 × 每个位置 10 条**；同一文档明确记录了 **25 条不够、效果很差**。evidence: [T03-S038]"
  "**边采边做质量筛查**（角色：数据运营）。宇树的「机器人数据运营工程师」岗位职责把这条写得很直白：负责数据采集、清洗、审核、标注、归档、上传全流程，**制定采集规范、质量评估标准与数采员培训教程**，并处理采集过程中的硬件异常与通信故障。另设「具身数据评估工程师」负责自动化数据筛选、难例挖掘与负样本生成。evidence: [T03-S058]"
  "**训练与配比**（角色：算法工程师）。当前默认路径是「大规模预训练 + 小规模后训练」：π0 的配方是先在跨本体大数据上预训练，再用小批高质量数据后训练到具体任务；openpi 的官方口径是**用自己平台 1–20 小时的数据微调即可覆盖多种任务**。evidence: [T03-S035, T03-S033, T03-S034]"
  "**真机评测并回填**（角色：评测负责人）→ 工作流 9。把失败案例转成下一批采集的目标场景。"
  "**决定停止条件**（角色：算法负责人）。见下面「什么时候该停止采数据」。"
)
declare -a FAILURE_MODES=(
  "**只报条数不报多样性**（本行第 15 号破绽）：「我们采了 10 万条」而答不出多少任务、多少场景、多少物体、几个采集员、成功轨迹占比、平均时长。evidence: [T06-S044]"
  "**把小时数当有效数据**：采集小时 ≠ 有效小时 ≠ 训练可用小时，三个口径要分开报。"
  "**中途改硬件/改相机位置**：历史数据贬值，且经常没人算这笔账。"
  "**用数据补硬件的账**：抓不稳就多采，实际该换爪或加力控。"
  "**随机切分做验证集**：同一场景的相邻帧同时进训练与验证，指标虚高。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
