#!/usr/bin/env bash
# workflow-4.sh — 环境搭建与标定（手眼、工件坐标系、力传感器、重复性验收） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="环境搭建与标定（手眼、工件坐标系、力传感器、重复性验收）"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "环境搭建与标定（手眼、工件坐标系、力传感器、重复性验收）" 工作流。

一句话: 从「硬件装好了」到「所有坐标系互相对齐、传感器读数可信、重复性有实测报告」——之后的所有算法工作才有意义。

入门 SOP 共 7 步, 失败模式自检 5 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**相机内参标定**（角色：视觉工程师）。输出：内参与畸变系数 + **重投影误差**统计。"
  "**手眼标定**（角色：视觉工程师）。eye-in-hand（相机装在末端）或 eye-to-hand（相机固定看机器人）。流程：贴/放标定靶 → 机器人走到若干位姿 → 每个位姿同时记录「末端在基座下的位姿」与「靶在相机下的位姿」→ 求解 AX=XB。MoveIt 的手眼标定插件在采到 **5 组**样本后即可求解，默认用 Daniilidis 解算器。evidence: [T03-S016, T03-S017]"
  "**TCP（工具中心点）与负载/重心标定**（角色：机械/调试工程师）。多数厂商控制器有内置的多点法 TCP 标定与负载辨识向导，国内厂商手册里同样有这一节。evidence: [T03-S055, T03-S056]"
  "**工件/工装坐标系建立**（角色：调试工程师）。三点法或用定位销/基准面。输出：工件系相对基座系的变换。"
  "**力/力矩传感器标定与重力补偿**（角色：控制工程师，仅力控应用）。零偏、温漂、工具重力与重心补偿；标定后要在多个姿态下验证「空载读数接近零」。"
  "**重复性/精度实测验收**（角色：质量）。按 ISO 9283 / GB/T 12642 的方法：在工作空间最大内接立方体上取 5 个位姿、每个位姿 30 次，重复性按到质心平均距离加 3 倍标准差计。evidence: [T06-S006, T06-S089]"
  "**写「重标触发清单」并交给现场**（角色：调试工程师）。典型触发：撞机、换末端、换相机或镜头、拧过相机支架、大修、环境温度显著变化、精度巡检超差。"
)
declare -a FAILURE_MODES=(
  "**只采 5 组样本、位姿分布集中**：残差看着小，换个工作区域就偏。破解：位姿覆盖实际作业区、姿态角拉开、样本数远超求解下限。evidence: [T03-S016, T03-S020]"
  "**标定靶不平/靶尺寸录错**：整套外参有系统性偏置。破解：先用已知距离验证靶的尺度。"
  "**相机支架不刚**：标定当天好，一周后偏。破解：把支架刚度与是否被人碰过列入巡检项。"
  "**标定与作业的温度状态不同**：冷机标定、热机作业。evidence: [T03-S019]"
  "**没有基线报告**：后期良率下降时无法判断是不是标定退化。evidence: [T06-S006]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
