#!/usr/bin/env bash
# workflow-3.sh — 误差预算与硬件选型（从末端精度反推） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="误差预算与硬件选型（从末端精度反推）"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "误差预算与硬件选型（从末端精度反推）" 工作流。

一句话: 从「工艺要求的末端容差」反推出一张误差分配表，据此决定相机选型、标定方案、结构刚度、工装定位方式与是否需要力控/柔性补偿。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**写下工艺容差与判定方式**（角色：工艺）。例如插入间隙、涂胶宽度、拧紧同轴度。输出：一个数字 + 一个测法。"
  "**列全误差源，逐项给量级**（角色：视觉/机械工程师）。至少要有：相机的 precision（重复性/噪声）与 trueness（与真值的偏差）、内参与畸变残差、手眼标定残差、机器人**绝对**定位误差（不是重复定位精度）、结构与工装的定位误差、热漂移、抓取后工件在爪内的位姿变化。evidence: [T03-S018, T03-S020, T06-S085]"
  "**合成误差并留余量**（角色：视觉工程师）。明确写清哪些项按方和根（独立随机）合成、哪些按最坏情况直接相加（系统性偏置）。"
  "**决定用「绝对精度路线」还是「相对精度路线」**（角色：方案工程师）。相对路线（视觉在抓取/装配点附近再看一次、做视觉伺服或力控找正）可以绕过机器人绝对精度这一大项；绝对路线必须做运动学标定并接受成本。"
  "**决定容差归谁吃**（角色：机械 + 工艺）。柔性夹爪、浮动法兰、导向倒角、力控搜孔都可以把一部分几何误差转成「机构吸收」。刚性爪 + 金属件几乎没有余量。evidence: [T03-S018]"
  "**写出验收测法**（角色：质量）。规定在哪些位姿、测多少次、按什么统计量判定。工业侧可直接借用 ISO 9283 / GB/T 12642 的测试立方体与「5 个位姿 × 30 次」的做法。evidence: [T06-S006, T06-S089, T03-S053]"
)
declare -a FAILURE_MODES=(
  "**把 repeatability 当 accuracy 用**（本行第一号外行破绽）。破解：任何精度数字都追问「重复性还是绝对精度？按 ISO 9283 在什么条件下测的？」evidence: [T06-S044, T06-S006]"
  "**相机 precision 好就以为 trueness 好**：点云噪声小不代表尺度与形状忠实；bin picking 里 trueness 误差直接变成抓偏。evidence: [T03-S018]"
  "**手眼标定只采 5 组就收工**：工具最少样本数（MoveIt 默认 5 组即可求解）是**能算**的下限，不是**能用**的下限。evidence: [T03-S016, T03-S020]"
  "**忽略工件在爪内的二次误差**：装配阶段才发现每次插入都偏，误以为是视觉问题。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
