#!/usr/bin/env bash
# workflow-13.sh — 演示与交付验收（POC vs 量产） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="演示与交付验收（POC vs 量产）"

usage() {
  cat <<EOF
workflow-13.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-13.sh             # interactive
  ./workflow-13.sh --dry-run
  ./workflow-13.sh --json
  ./workflow-13.sh --explain
  ./workflow-13.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "演示与交付验收（POC vs 量产）" 工作流。

一句话: 从「一个能拍视频的 demo」到「一份不会被 demo 骗的验收标准」，以及从 POC 到量产验收之间那道最容易被跳过的闸门。

入门 SOP 共 6 步, 失败模式自检 6 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**把每条验收指标写成「定义 + 测法 + 样本量 + 判定 + 责任人」**（角色：项目经理 + 客户）。集成商侧的实践是：每个验收点都对应一条书面需求、一个测试步骤和一个具名责任人；过程 run-off 的验收准则要写成具体的东西（例如焊缝质量、循环时间、重复性）。evidence: [T03-S061]"
  "**成功率必须带分母**（角色：项目经理）。写清任务定义、试验次数、初始状态分布、判定标准、是否允许重试、是否有人在旁。evidence: [T06-S044]"
  "**把人工介入写成独立条款**（角色：项目经理）。规定：哪些介入允许、每班允许多少次、介入后是否仍计成功、遥操作兜底是否算交付范围。**「有人接管」的成功不计入自主成功率。** evidence: [T06-S044]"
  "**加连续运行条款**（角色：客户质量 + 项目经理）。规定连续跑多长时间、允许多少次停机、恢复时间上限。"
  "**加换型与异常条款**（角色：客户工艺）。换型时间上限 + 由客户操作工独立完成 + 每类异常的恢复时间。evidence: [T06-S044]"
  "**写清不通过的处理**（角色：商务）。整改期限、复测规则、部分验收与扣款方式。"
)
declare -a FAILURE_MODES=(
  "**用 demo 条件写验收**：固定摆位、挑过的件、工程师在旁。evidence: [T06-S044]"
  "**只验单次成功不验连续运行**。evidence: [T06-S044]"
  "**不写干预条款**：交付后才发现每小时要人管两次。evidence: [T06-S044]"
  "**把「实训/试点」当成「上线」写进宣传与合同**。evidence: [T03-S073, T03-S075]"
  "**验收指标写成形容词**（「运行平稳」「效果良好」）。"
  "**只报仿真或只报最好的一次**（技术诚信红线）。evidence: [T06-S044]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-13-walkthrough"
fi
