#!/usr/bin/env bash
# workflow-2.sh — 形态与本体选型（含成本与工期账） SOP walkthrough for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
WORKFLOW="形态与本体选型（含成本与工期账）"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "形态与本体选型（含成本与工期账）" 工作流。

一句话: 从「任务书」到「选定形态（专机 / 工业臂 / 协作臂 / 移动操作 / 足式 / 人形）+ 具体型号 + 一张带工期的成本表」。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**按「作业空间 × 变异度 × 节拍」先定形态类别**（角色：方案工程师）。"
  "**按「人机是否共享空间」而不是按「是不是协作臂」定安全路线**（角色：安全工程师）。协作是**应用属性**，同一台协作臂装上刀具或高速搬运就不再是协作应用。evidence: [T06-S003, T06-S026, T03-S023]"
  "**列候选型号，按规格书的**真实**口径比较**（角色：方案工程师）。重复定位精度必须问清是按 ISO 9283 / GB/T 12642 在什么负载、什么速度、哪个测试立方体测的；额定负载必须问重心偏置与转动惯量。evidence: [T06-S006, T06-S048, T06-S044]"
  "**同步定末端工装（EOAT）与来料呈现方式**（角色：机械工程师）。末端与工装通常是项目中最贵、最容易返工的部分，且**系统故障主要来自末端工装、视觉、上下料与线缆，不是本体**。evidence: [T06-S044]"
  "**出成本表与工期，并写清被否形态**（角色：项目经理）。"
)
declare -a FAILURE_MODES=(
  "**「人形/通用机器人先买一台试试」**：人形当前的商业部署普遍是**限定工位、限定任务、有人陪同**，且中文语境里的「进厂」经常指「实训」而不是常态化生产。选型阶段要把「实训」和「上线」分开写。evidence: [T03-S073, T03-S075, T06-S044]"
  "**把订单量/产能当部署量**：厂商公布「第 1000 台下线」是产能口径，不是「1000 台在产线上干活」。evidence: [T03-S074, T06-S044]"
  "**7 轴当成更高精度买**：7 轴的价值是冗余（避奇异、避障、避关节限位），不是精度。evidence: [T06-S044]"
  "**用协作臂做高节拍**：安全限速一开，节拍直接不达标；再调高速度就要重做风险评估与力/压强实测。evidence: [T03-S024, T06-S003]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
