#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for 招聘与猎头.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="招聘与猎头"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 8 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 8 条规则:
  • 如果  → 则 用人经理给你的是一份形容词清单（有大厂背景、稳定、有 0-1 经验），**则**先不要开跑，回到 intake 把它逼成
  • 如果  → 则 要提升单场面试的准确度而预算为零，**则**先做「评分提交前不许互相讨论」这一件事，它不花钱且直接命中结构化的评价侧 e
  • 如果  → 则 你在做渠道预算分配，**则**看分渠道的分阶段通过率，不要只看最终录用数 evidence: [T06-S049, T0
  • 如果  → 则 候选人在终面前后开始犹豫，**则**处理的是离职阻力而不是薪酬数字，**并且**要在发 offer 之前就把 count
  • 如果  → 则 你要上任何一个自动打分、排序或筛选候选人的工具，**则**先确认它落在哪几部法规下，并且把审计与告知义务写进采购条件 e
  • 如果  → 则 有人拿一个招聘指标跟你比较（周期、接受率、成本），**则**先问分子分母再看数字 evidence: [T06-S049
  • 如果  → 则 候选人是被挖过来的明星，**则**把谈判重心从薪酬移到平台条件——他带谁来、接谁的资源、前九十天谁给他开门 eviden
  • 如果  → 则 一个岗位跑了六周还是零 offer，**则**回到 intake 改需求，而不是加大触达量 evidence: [T03

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a RULE_ACTIONS=(
  "用人经理给你的是一份形容词清单（有大厂背景、稳定、有 0-1 经验），**则**先不要开跑，回到 intake 把它逼成「前九十天要做成的三件事」evidence: [T03-S001, T03-S011]"
  "要提升单场面试的准确度而预算为零，**则**先做「评分提交前不许互相讨论」这一件事，它不花钱且直接命中结构化的评价侧 evidence: [T04-S010, T03-S024]"
  "你在做渠道预算分配，**则**看分渠道的分阶段通过率，不要只看最终录用数 evidence: [T06-S049, T03-S004]"
  "候选人在终面前后开始犹豫，**则**处理的是离职阻力而不是薪酬数字，**并且**要在发 offer 之前就把 counter-offer 演练过 evidence: [T03-S040, T03-S039]"
  "你要上任何一个自动打分、排序或筛选候选人的工具，**则**先确认它落在哪几部法规下，并且把审计与告知义务写进采购条件 evidence: [T02-S056, T06-S010]"
  "有人拿一个招聘指标跟你比较（周期、接受率、成本），**则**先问分子分母再看数字 evidence: [T06-S049, T06-S046]"
  "候选人是被挖过来的明星，**则**把谈判重心从薪酬移到平台条件——他带谁来、接谁的资源、前九十天谁给他开门 evidence: [T04-S006, T01-S029]"
  "一个岗位跑了六周还是零 offer，**则**回到 intake 改需求，而不是加大触达量 evidence: [T03-S001, T03-S004]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
