#!/usr/bin/env bash
# workflow-5.sh — 数据采集与数据管理 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="数据采集与数据管理 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "数据采集与数据管理 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 7 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**写一份数据管理计划**（哪怕只有两页）。交付物：写清会产生什么数据、格式与体量、怎么命名与组织、存在哪里、谁能访问、保存多久、最终共享到哪个仓储、共享的限制与理由。做完的标准：一个新来的人照着它能找到任何一份数据 \`evidence: [T03-S025, T03-S026]\`。"
  "**定目录结构与命名规则，写进一份 README**。交付物：固定目录树（原始 / 中间 / 结果 / 代码 / 文档）+ 命名规范（含日期格式、版本号、无空格无中文路径）。做完的标准：文件名本身能告诉你是什么、什么时候、第几版。"
  "**原始数据只读**。交付物：一份不可修改的原始数据副本（另存一处、设只读、留校验值）。做完的标准：任何清洗与修正都发生在脚本里，原始文件从头到尾没被改过。"
  "**清洗与转换全部脚本化**。交付物：从原始数据到分析数据集的可重跑脚本。做完的标准：删掉所有中间文件后跑一条命令能全部重建。"
  "**版本控制与备份分开做**。交付物：代码与文本进版本控制系统；数据按 3-2-1 之类的规则备份（多份、不同介质、异地一份）。做完的标准：误删一个目录不会毁掉项目。"
  "**留痕**。交付物：一份决策日志（时间、改了什么、为什么），以及采集端的原始记录（纸质或电子实验记录本、问卷后台导出、设备日志）。做完的标准：三年后被问「这个被排除的样本为什么排除」能答。"
  "**归档与共享**。交付物：数据集存入有持久标识符的仓储、拿到 DOI、写好元数据与许可；论文里写数据可用性声明。做完的标准：别人拿着 DOI 能找到并知道能怎么用 \`evidence: [T03-S034, T03-S044]\`。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**单人或小组规模、社科问卷或计算类项目**：写一份两页的数据管理计划 2–5 天；搭目录结构与命名规范 1 天；把清洗脚本化通常与分析并行、占分析总时长的 30%–50%（这是常见经验分布不是测量值）；归档与元数据整理在投稿前后 1–2 周。**生医湿实验项目**的采集端留痕（实验记录本、仪器原始文件）是持续性工作，不能压缩成一个阶段；**多中心临床研究**的数据管理是独立岗位的工作量，不适合用上面任何数字类比。"
  "**中国侧差异**:"
  "数据出境是国内独有的强约束：国际仓储（含通用型代码与数据仓储）对涉及人类遗传资源信息的数据不是默认可用选项，须先走事先报告与信息备份 \`evidence: [T03-S018]\`。务实做法是在数据管理计划里就分层——哪一层可公开、哪一层只能受控访问、哪一层只能在境内。"
  "国内资助机构对数据管理计划的强制程度普遍弱于 NIH 之类的口径，很多项目不会主动要求；但投国际期刊时期刊会要，所以这份计划要为投稿而写而不是为结题而写。"
  "高校普遍缺少机构级数据仓储，实践中依赖课题组自建与商业网盘，这带来两个具体风险：网盘的版本冲突，以及个人账号离职即失效。把「机构可长期维护的存储位置」写进计划，而不是写某个人的网盘。"
  "**近期变化**: \`last_updated: 2026-09\`。两条：资助机构侧在收紧——NIH 在 2026 年通过 NOT-OD-26-046 更新 DMS Plan 要素并强制格式页，方向是「更短、更结构化、更可审」\`evidence: [T03-S026]\`；期刊侧在把数据与代码可用性从「声明」推向「可核验」，越来越多刊要求提供可访问的仓储链接而不是「合理要求下可向作者索取」这种表述 \`evidence: [T03-S039, T03-S028]\`。"
  "evidence: [T03-S025, T03-S026, T03-S034, T03-S018, T03-S019, T03-S039]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
