#!/usr/bin/env bash
# workflow-1.sh — 选题与可行性判断 (Decay risk: low) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="选题与可行性判断 (Decay risk: low)"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "选题与可行性判断 (Decay risk: low)" 工作流。

入门 SOP 共 6 步, 失败模式自检 7 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**把兴趣写成一句「谁在什么条件下会怎样」的陈述句**。交付物：一页纸，写清研究对象、变量或现象、你猜的方向。做完的标准：这句话可以被证伪——如果结果反过来，你能说出「那我就错了」。"
  "**做一次「已经有人做过吗」的窄检索**。交付物：20–40 条题录 + 5–8 篇细读的核心文献 + 一段「现有工作停在哪」。做完的标准：你能说出最近三年最接近的那篇是谁做的、它没回答什么。"
  "**把问题降级成一个可测的具体问题**。交付物：一句可操作化的问题（谁 / 什么测量 / 什么比较 / 什么结局）。做完的标准：能写出主结果那张图的横纵轴。"
  "**做「三种结果」演练**。交付物：一段文字，分别写「显著正向 / 无效应 / 反向」三种结果各自意味着什么。做完的标准：三种结果都有话可说——只有一种结果能写成论文的题目不要做。"
  "**可行性核对表**：数据 / 样本 / 设备 / 经费 / 伦理 / 时间 / 技能 / 合作者，逐项写「已有 / 需申请 / 无解」。交付物：一张表。做完的标准：没有「无解」项，或每个「无解」项都有 plan B。"
  "**和导师或一位圈内人做一次 15 分钟口头汇报**。交付物：对方能复述你的问题。做完的标准：对方提出的第一个反对意见你答得上来。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**社科与实验心理学方向的博士生第一个独立课题**：一页纸问题陈述 1–2 周，窄检索与细读 2–4 周，可行性核对 1 周，合计约 1–2 个月。**生医湿实验方向**因为要预估试剂、动物与伦理批件周期，可行性核对本身常再加 2–4 周。**计算与工程方向**若数据集与基线代码公开可得，整个阶段可以压到 2–3 周，但要额外花时间确认数据集许可与使用条款。这些是常见区间不是保证值，跨学科不可直接套用。"
  "**中国侧差异**:"
  "英文攻略默认「你自己选题」；国内硕博的题目相当比例来自导师在研项目的子课题，可协商空间在「怎么切」而不是「做不做」。开题报告与培养方案里的时间节点是硬的，不能按英文攻略那种「想清楚再开工」的节奏走。"
  "破除「唯论文」的 2020 年两份文件把评价导向从数论文转向代表作，但落到具体单位的博士毕业与考核细则上执行程度差异很大——选题前应当去查**本单位现行**的学位与考核文件，而不是套用国家层面的原则 \`evidence: [T03-S022]\`。"
  "涉及人工智能、算法与个人数据处理的研究在中国明确纳入科技伦理审查范围，而按美国联邦通则的豁免类别读英文攻略会误以为纯数据研究不需审查——这是选题阶段最常见的时间表误判 \`evidence: [T03-S016, T03-S035]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。近 24 个月最大的变化有两条：一是生成式模型让「快速摸清一个陌生领域」的成本骤降，但也让「看起来有据可查、实则引文不存在」的选题依据变多，所以第 2 步的每一条关键文献都必须回到原文确认；二是主要出版商与医学期刊编辑规范陆续把 AI 使用的披露写进正式条款（ICMJE 2026 年 1 月版把 AI 单独成节），选题阶段就该决定这条线上要不要用、怎么记录 \`evidence: [T03-S010, T03-S039]\`。"
  "evidence: [T03-S016, T03-S033, T03-S013, T03-S022, T03-S010]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
