#!/usr/bin/env bash
# workflow-12.sh — 实验室协作与署名协商 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="实验室协作与署名协商 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-12.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-12.sh             # interactive
  ./workflow-12.sh --dry-run
  ./workflow-12.sh --json
  ./workflow-12.sh --explain
  ./workflow-12.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "实验室协作与署名协商 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**开工前谈署名**。交付物：一份书面记录（邮件即可）——预期的作者名单与顺序、通讯作者是谁、依据是什么、什么情况下会调整。做完的标准：每个人都回复确认过 \`evidence: [T03-S011]\`。"
  "**同时定贡献口径**。交付物：用贡献者角色分类法把 14 类角色分配到人（谁负责构思、方法、软件、验证、数据管理、写作原稿、写作审阅与编辑等）。做完的标准：这份表将来可以直接变成论文的贡献声明 \`evidence: [T03-S012]\`。"
  "**定数据与代码的归属与交接规则**。交付物：一段说明——数据存在哪、谁能访问、离组时怎么交接、发表后归档在哪。做完的标准：任何人明天离开，工作都能继续。"
  "**定沟通节奏**。交付物：组会频率与形式、进度记录在哪、决定写在哪。做完的标准：三个月后能查到「当时为什么这么定」。"
  "**跨单位合作先签好条件**。交付物：合作协议或至少一份书面备忘——各方投入、成果归属、署名、数据共享与出境的限制。做完的标准：涉及人类遗传资源或个人信息的部分已按法规走完审批或备案路径 \`evidence: [T03-S018, T03-S019]\`。"
  "**定期复核**。交付物：项目中期把第 1 步的记录拿出来对一次，按实际贡献调整并重新确认。做完的标准：调整有记录、有各方确认，不是口头默认。"
  "**通讯作者明确责任**。交付物：一句话——通讯作者对全文的完整性与准确性负责、负责与期刊沟通、负责保存原始数据、负责回应发表后的问询。做完的标准：担任这个角色的人知道这不是荣誉而是责任 \`evidence: [T03-S011, T03-S009]\`。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**协商与制度动作本身，不是研究周期**：开工前的署名与贡献协商一次会议 + 一封确认邮件，通常 1–2 小时；课题组书面手册首次撰写 1–2 天，之后每年更新一次；跨单位合作协议从起草到签署，在国内高校常见为**数周**（需过科研处与法务）；**涉及人类遗传资源的国际合作审批或备案要按数月预留**，这是最容易被低估的一项 \`evidence: [T03-S018]\`。争议一旦进入机构调查程序，时间尺度完全由程序决定，个人无法压缩。"
  "**中国侧差异**:"
  "师门结构与英文攻略假设的 PI-postdoc-student 关系不同：导师在署名、课题分配、毕业时间上的实际权重更大，学生的议价空间更小。这不改变规则（四条标准是一样的），但改变可行策略——**书面记录的价值在国内更高**，因为它是争议发生时唯一可核查的东西。"
  "「导师挂通讯作者、学生一作」是国内的常见默认，但它不能替代逐条核对四条标准；同样，把不参与工作的人加进作者名单在国内被明确列为失信行为，不存在「行业惯例」的豁免 \`evidence: [T03-S021]\`。"
  "高校处理学术不端与署名争议有专门的部门规章（教育部令第40号，2016 年施行且现行有效），程序上由学校学术委员会负责，与科技伦理委员会是两套体系 \`evidence: [T03-S022]\`。"
  "学位论文另有独立的作假处理办法与抽检制度，学生的学位论文与期刊论文的责任边界与英文语境不同 \`evidence: [T03-S081, T03-S082]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：AI 使用的责任归属成为新的协商项——中国科学院科研道德委员会发布过规范使用人工智能技术的诚信提醒，主要出版商也统一规定 AI 不能作为作者，课题组需要在开工时就约定谁负责披露、披露到什么粒度 \`evidence: [T03-S079, T03-S039, T03-S010]\`；教育部在 2024 年发文加强高校科研诚信建设与学术不端治理，各高校近两年在陆续落成本单位实施细则，本单位规则的更新频率高于国家文件 \`evidence: [T03-S080]\`；科技部有科研单位科研诚信管理制度的示范文本可参照，课题组手册可以直接对齐 \`evidence: [T03-S071]\`。"
  "evidence: [T03-S011, T03-S012, T03-S014, T03-S021, T03-S022, T03-S018, T03-S073, T03-S079, T03-S080]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-12-walkthrough"
fi
