#!/usr/bin/env bash
# workflow-6.sh — 分析与稳健性检验 (Decay risk: low) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="分析与稳健性检验 (Decay risk: low)"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "分析与稳健性检验 (Decay risk: low)" 工作流。

入门 SOP 共 7 步, 失败模式自检 7 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先看数据再看结论**。交付物：描述性统计、分布图、缺失模式、异常值清单。做完的标准：知道每个变量长什么样，不是直接跑模型。"
  "**按预先写好的分析计划跑主分析**。交付物：主结果（效应量 + 不确定性区间，而不只是 p 值）。做完的标准：这一步没有任何未记录的选择。"
  "**把探索性分析物理隔开**。交付物：两个分开的脚本或两个分开的结果小节。做完的标准：读者能一眼分清哪些是预先说好的、哪些是看了数据之后做的 \`evidence: [T03-S027]\`。"
  "**做稳健性检验**。交付物：一张表或一张图，展示结论在不同合理选择下怎么变（不同协变量集、不同异常值规则、不同模型设定、不同缺失处理）。做完的标准：能说出「在哪些设定下结论会翻」。"
  "**处理多重比较**。交付物：说明做了多少个检验、用什么方式控制（预先指定主结局、族错误率控制、错误发现率控制、或明确声明为探索性不做校正）。做完的标准：不出现「我只跑了一个检验所以没有多重比较问题」这种说法——分析选择是看了数据之后定的，一类错误率照样被抬高。"
  "**写解释纪律**。交付物：结果段落只描述观察到什么，不加因果词；讨论段落才谈解释并注明其依据。做完的标准：不显著不写成「有变好的趋势」，显著不写成「证明了」。"
  "**可重复性自检**。交付物：从原始数据一条命令跑到论文里每个数字的脚本 + 环境记录（软件版本、随机种子）。做完的标准：换一台机器能跑出一样的数。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**社科 / 心理学的单个实验或调查数据集**：描述性检查 2–5 天，主分析 1–2 周，稳健性检验 1–3 周，可复现脚本整理 3–7 天。**生物信息与计算方向**的分析时间主要花在流水线搭建与算力等待上，与上面不同量级。**临床试验的统计分析**由统计师按预先锁定的分析计划执行，锁库到出主结果的节奏由方案规定，不适用上述任何数字。"
  "**中国侧差异**:"
  "国内课程体系里统计训练在很多院系偏薄，实践中大量依赖统计咨询与外包分析。外包本身不违规，但**必须**保证作者中有人能对分析负责并解释每一步——找不出这个人时，署名与责任就出了问题 \`evidence: [T03-S011]\`。"
  "「统计显著」在国内的评价与答辩语境里仍有很强的话语权，导致不显著结果被弃置的压力比英文攻略描述的更大。务实做法是在开题时就把不显著结果的去处想好（注册报告、预印本、或作为方法学贡献发表）。"
  "中文期刊与国际期刊对统计报告的严格程度差异明显，按国际规范做的分析在投国内刊时可能被要求「简化」，这时不要删掉不确定性区间与稳健性检验，可移入附录。"
  "**近期变化**: \`last_updated: 2026-09\`。两条：多重宇宙 / 规格曲线一类的稳健性分析在近 24 个月从社科扩散到计算社会科学与更广的实证领域，并出现了跨学科的方法指南与专门讨论其可视化的研究，说明它正在从「加分项」变成「被审稿人问到就得有」\`evidence: [T03-S046, T03-S047]\`；同时生成式模型进入分析环节，带来一个新的报告要求——哪一步用了模型、模型版本是什么、人工核对了什么，主要出版商的编辑政策已把 AI 使用的披露写进条款 \`evidence: [T03-S039, T03-S010]\`。"
  "evidence: [T03-S050, T03-S027, T03-S046, T03-S047, T03-S028, T03-S003]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
