#!/usr/bin/env bash
# workflow-2.sh — 文献综述与系统综述 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="文献综述与系统综述 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "文献综述与系统综述 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 7 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先判定你要做哪一种**。交付物：一句话说明——「这是给论文写引言的叙述性综述」还是「这是要独立发表、需要注册与报告规范的系统综述」。做完的标准：如果是后者，你已经知道要遵 PRISMA 2020 并准备注册 \`evidence: [T03-S002]\`。"
  "**写检索式，而不是「搜关键词」**。交付物：一份可复制的检索式（数据库名 + 完整检索串 + 字段限定 + 时间范围 + 语言限定 + 执行日期）。做完的标准：把这段交给另一个人，他跑出来的条数和你差不多。"
  "**多库检索并保留原始导出文件**。交付物：每个数据库一个导出文件（原始、不修改）+ 一份合并去重后的库。做完的标准：能说出各库各命中多少条、去重后剩多少条。"
  "**两级筛选：题摘筛 → 全文筛**。交付物：预先写好的纳入排除标准 + 每一条被排除文献的排除理由（尤其全文阶段）。做完的标准：能画出流程图的四个数字（识别 / 筛选 / 纳入资格 / 最终纳入）。"
  "**提取数据到结构化表**。交付物：一张提取表（每行一篇，列是你后面要用的字段）。做完的标准：不回原文就能做后续分析。"
  "**偏倚风险评估**（系统综述必做）。交付物：逐研究的偏倚评估结果表。做完的标准：结论里能区分「高质量研究说什么」和「所有研究平均说什么」。"
  "**写成有主线的综述而不是流水账**。交付物：按论点组织的段落，而不是按文献一篇一段。做完的标准：每一段的主题句是你的判断，引文是证据。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**健康与生医领域、有方法学支持的正式系统综述**：方案撰写与注册 2–6 周，检索与去重 1–3 周，双人题摘筛选（数千条量级）4–10 周，全文筛选与提取 4–12 周，偏倚评估与合成 3–8 周，写作 4–8 周——这类综述常见的总跨度以**月到一年以上**计，是一项独立研究而不是论文的准备工作。**社科的叙述性综述或论文引言的文献工作**通常 2–6 周。**计算与工程领域的系统文献综述**（software engineering 传统的 SLR）介于两者之间。不要把任何一条当成跨学科通用值。"
  "**中国侧差异**:"
  "中文文献是很多社科与临床题目绕不过去的一块，但主要中文库的检索语法与导出格式和国际库不同，去重时作者姓名与机构字段常对不齐——检索式要中英文各写一套并分别记录。"
  "国内的开题报告与基金本子的「国内外研究现状」有固定写法预期（先国外后国内、分段总结、末尾点出空白），这与英文期刊引言的漏斗结构不是一回事，两者不要互相套用。"
  "主要出版商与 EQUATOR 都有报告规范的中文译本索引，可以用中文清单自查、用英文原文引用 \`evidence: [T03-S001, T03-S052]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。两条：一是 AI 辅助筛选与数据提取已经从「能不能用」进入「怎么报告」阶段——PRISMA 2020 已要求说明自动化工具的使用，现在期刊进一步要求写清哪一步用了什么模型、人工复核比例多少 \`evidence: [T03-S002, T03-S039]\`；二是论文工厂产出的低质量文献大量进入检索结果，纳入前多了一道新工序：查该文献是否已被撤稿或已有公开质疑，撤稿文献若被纳入合并，结论会被直接推翻。"
  "evidence: [T03-S002, T03-S001, T03-S033, T03-S039, T03-S013]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
