#!/usr/bin/env bash
# workflow-13.sh — 出错之后：更正、关注声明、撤稿与举报 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="出错之后：更正、关注声明、撤稿与举报 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-13.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-13.sh             # interactive
  ./workflow-13.sh --dry-run
  ./workflow-13.sh --json
  ./workflow-13.sh --explain
  ./workflow-13.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "出错之后：更正、关注声明、撤稿与举报 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先判断错误的性质与影响**。交付物：一段书面判断——错在哪一步（数据、分析、报告、图）、影响哪些结论、如果读者当初就知道，结论会不会实质改变。做完的标准：能回答「结论还成立吗」这一个问题 \`evidence: [T03-S015]\`。"
  "**保全证据**。交付物：原始数据、分析脚本、通信记录的完整副本与时间戳，任何人不得修改。做完的标准：这份材料能交给第三方复核。"
  "**告知共同作者与所在单位**。交付物：书面告知与各方确认。做完的标准：没有人是在期刊发通知时才知道。"
  "**主动联系期刊编辑**。交付物：一封说明信——发现了什么、怎么发现的、影响范围、你建议的处理方式（更正 / 撤稿）与理由 + 支持材料。做完的标准：由你而不是由举报者把事实摆到编辑桌上。"
  "**配合编辑的处理路径**。交付物：按编辑要求提供的原始数据与说明。做完的标准：理解三条路径的分界——结论不受实质影响的走**更正**；事实尚待查清、需要时间的走**关注声明**；结论已不可靠的走**撤稿** \`evidence: [T03-S015, T03-S014]\`。"
  "**接受结果并把它写进自己的记录**。交付物：更正或撤稿通知的链接；在个人主页与简历里如实标注。做完的标准：不隐瞒——主动更正的记录在同行眼里是加分不是减分。"
  "**如果是要报告别人的问题**：先分清是学术分歧还是可能的失信行为；前者走公开学术讨论（评论、回应、发表后评议），后者按被指对象所在单位与期刊的正式渠道提交，写清具体证据与出处，不做超出证据的断言。做完的标准：你的材料能被第三方独立核验 \`evidence: [T03-S021, T03-S077, T03-S078]\`。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**编辑部与机构的程序时长，由程序决定而非作者**：出版伦理机构的指南本身指出，当调查或解决一项可信质疑需要相当时间（例如数月）时应先发关注声明——这句话本身说明这类流程的量级是**月到年**。机构调查的时长按各国各单位的程序规定，中国侧按《科研失信行为调查处理规则》的程序办理。作者侧能控制的只有前四步：从发现问题到把说明信发给编辑，**应当以天到周计而不是以月计** \`evidence: [T03-S015, T03-S021]\`。"
  "**中国侧差异**:"
  "有**成体系的国家级程序规则**（2022 年的调查处理规则）与高校部门规章（教育部令第40号），以及资助机构的独立处理办法与具名通报——这套制度密度高于多数英文攻略描述的情形 \`evidence: [T03-S021, T03-S022, T03-S066, T03-S067]\`。"
  "「五不准」（不准由第三方代写、不准由第三方代投、不准由第三方对论文内容进行修改、不准提供虚假同行评审人信息、不准违反论文署名规范）是国内研究者需要能背下来的五条硬红线 \`evidence: [T03-S021]\`。"
  "学位论文另有作假行为处理办法（教育部令第34号）与抽检制度，责任链条与期刊论文不同 \`evidence: [T03-S082, T03-S081]\`。"
  "举报渠道在国内是本单位科研诚信责任主体 + 上级主管部门 + 资助机构三条线，与英美的机构办公室加联邦监管机构的结构不同；材料的可核验性要求是一样的。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：出版伦理机构在 2025 年发布修订版撤稿指南，新增了针对论文工厂与第三方的处理内容，这是近 24 个月最直接影响流程的一次改版 \`evidence: [T03-S037, T03-S015]\`；撤稿与更正数据已进入公开的元数据接口并每工作日更新，任何人都能按 DOI 查一篇论文是否被撤稿或更正——引用前查一遍已经成为可执行的常规动作 \`evidence: [T03-S075, T03-S086, T03-S076]\`；中国侧近两年持续在把国家规则落成单位实施细则并建立年度报告制度，本单位规则的变化比国家文件快 \`evidence: [T03-S080, T03-S071]\`。"
  "evidence: [T03-S015, T03-S037, T03-S021, T03-S022, T03-S066, T03-S067, T03-S075, T03-S076, T03-S077, T03-S087]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-13-walkthrough"
fi
