#!/usr/bin/env bash
# workflow-11.sh — 基金申请 (Decay risk: high) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="基金申请 (Decay risk: high)"

usage() {
  cat <<EOF
workflow-11.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-11.sh             # interactive
  ./workflow-11.sh --dry-run
  ./workflow-11.sh --json
  ./workflow-11.sh --explain
  ./workflow-11.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "基金申请 (Decay risk: high)" 工作流。

入门 SOP 共 8 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先读规则再想内容**。交付物：目标资助机构当年度的申请须知 / 项目指南 / 政策总纲的关键条款摘录——申请人资格、限项要求、经费科目、提交截止时间、依托单位的内部截止时间。做完的标准：你知道自己**有没有资格**申请，以及本单位比机构截止日提前多久 \`evidence: [T03-S064, T03-S024, T03-S068, T03-S069]\`。"
  "**把科学问题写成一句话**。交付物：一句话——本项目要回答什么、为什么现在、为什么是你。做完的标准：非本方向的同行听完能复述。"
  "**写立项依据**。交付物：国内外研究现状 → 关键科学问题 → 本项目的切入点。做完的标准：现状综述的落点就是你的问题，中间没有跳跃。"
  "**写研究方案**。交付物：研究内容、研究目标、拟解决的关键科学问题、研究方法与技术路线、可行性分析、创新点。做完的标准：每一条研究内容都对应一个可验证的产出。"
  "**写工作基础与研究条件**。交付物：前期结果（预实验数据最有说服力）、团队、平台、已有合作。做完的标准：能回答「凭什么是你能做成」。"
  "**做预算**。交付物：按当年度经费科目与比例限制编制的预算表 + 依据说明。做完的标准：每一笔都能说出算法，且符合当年度的科目口径（口径会变，必须按当年文件）。"
  "**形式审查自查**。交付物：一张自查表——签字盖章、附件齐全、限项、格式、字数、匿名要求（部分类型要求正文中不出现申请人信息）。做完的标准：把本单位科研处的退回原因清单逐条对完 \`evidence: [T03-S024]\`。"
  "**找人评一遍**。交付物：至少两位读者的意见——一位本方向、一位跨方向。做完的标准：跨方向的读者能说出你的创新点。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**中国国家自然科学基金面上 / 青年类项目的常见节奏**：集中接收期在每年上半年（**具体日期每年由当年通告规定，必须查当年文件，不能按往年推**）；从动笔到定稿，**首次申请者常见为 2–3 个月的断续投入**，有前一版本子的重写通常 3–6 周；依托单位的内部审核与提交需在机构截止日前预留时间（各单位不同，常见为提前一到两周）。评审与公布结果的周期由当年通告规定。**美国 NIH 类项目**的周期结构完全不同（有固定的多个接收轮次与再申请机制），不可用上面的数字类比。**社科类基金**的节点与理工类不同，同样按当年通告为准 \`evidence: [T03-S024, T03-S064, T03-S068]\`。"
  "**中国侧差异**:"
  "本子的文体是中国侧独有的：立项依据、研究内容、研究目标、拟解决的关键科学问题、技术路线、可行性分析、特色与创新、年度计划与预期成果——这是一套固定结构，与英文 proposal 的写法差异很大，照搬英文攻略会写出不符合评审预期的本子 \`evidence: [T03-S064]\`。"
  "**限项与资格规则**（一个人同时能申请与在研几项、哪些身份能申请）是国内特有的强约束，且逐年调整，必须查当年度通告 \`evidence: [T03-S024, T03-S065]\`。"
  "依托单位这一层是英文攻略里没有的：单位科研处的内部审核、盖章、系统提交都是关键路径，个人无法绕过。"
  "评审导向在跟着评价改革走：破除「唯论文」的 2020 年文件把代表作评价写进政策，资助机构近年也在公布年度改革举措，写本子时对「成果」的呈现方式应按当年度的口径而不是往年经验 \`evidence: [T03-S065, T03-S022]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：资助机构逐年发布改革举措，申请与评审的规则处在持续调整中，**往年经验的失效速度是本文件里最快的之一**——这也是本条工作流被标为高失效风险的原因 \`evidence: [T03-S065]\`；具名案件通报持续发布，构成可查证的红线判例 \`evidence: [T03-S067]\`；国际侧的数据共享与政策总纲同样逐年更新（2026 年有新版政策总纲与更新版数据管理计划要素），跨国合作项目要按申请当年的版本准备 \`evidence: [T03-S069, T03-S026]\`。"
  "evidence: [T03-S024, T03-S023, T03-S064, T03-S065, T03-S066, T03-S067, T03-S068, T03-S069, T03-S070, T03-S072]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-11-walkthrough"
fi
