#!/usr/bin/env bash
# workflow-3.sh — 研究设计与预注册 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="研究设计与预注册 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "研究设计与预注册 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**把假设写成可以被数据驳倒的形式**。交付物：编号的假设列表，每条注明是验证性还是探索性。做完的标准：每条假设都对应一个具体的统计检验或估计量。"
  "**选设计并说明为什么是它**。交付物：设计描述（随机对照 / 准实验 / 队列 / 横断 / 定性 / 混合等）+ 因果图或变量关系图。做完的标准：能说出这个设计控制了什么威胁、控制不了什么。"
  "**操作化：把概念变成测量**。交付物：每个变量的测量方式、量表来源、编码规则、缺失值定义。做完的标准：另一个团队用你的描述能测出同一个东西。"
  "**样本量论证**。交付物：目标样本量 + 依据（最小有实际意义的效应量、显著性水平、目标功效、或精度目标 / 贝叶斯停止规则 / 定性研究的饱和判据）。做完的标准：写清「我准备检出多小的效应」而不是「N=100 差不多」。"
  "**写分析计划**。交付物：主要结局与主要分析各一个、协变量清单、缺失数据处理、异常值规则、多重比较处理方式、稳健性检验清单。做完的标准：拿到数据后不需要再做任何未记录的选择。"
  "**决定注册路径并注册**。交付物：时间戳注册记录（OSF / AsPredicted / PROSPERO / 临床试验注册平台），或注册报告的 Stage 1 稿。做完的标准：注册在**收数据之前**完成，且有不可篡改的时间戳 \`evidence: [T03-S029, T03-S027]\`。"
  "**做一次小规模预实验或试点**。交付物：试点数据 + 修订记录。做完的标准：流程跑通、测量工具没崩、明确记录了哪些参数因试点而修改。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**社科与实验心理学的单个实验研究**：假设与设计成文 1–2 周，操作化与量表选定 1–2 周，样本量论证 2–5 天，分析计划 1 周，注册提交当天完成，试点 2–4 周，合计约 1.5–2.5 个月。**临床试验的方案（SPIRIT 口径）**因为要过伦理与注册平台，通常以**数月**计。**注册报告**要额外算上 Stage 1 的同行评审周期，这一段本身可能与一次普通投稿的审稿周期同量级，且各刊差异极大——各期刊自报的处理时长口径不同，不可合并成一个数字。"
  "**中国侧差异**:"
  "国内基金本子里的「研究方案」与英文语境的 protocol 不完全对应：前者更偏向说服评审人这条路可行，后者更偏向约束自己不许中途改。两份都要写时不要指望一稿两用。"
  "预注册在国内的制度激励弱：多数单位的考核不认注册记录，也不因为你预注册就宽限时间。做预注册目前主要是为了投国际期刊时的可信度与自我约束，不要期待本单位的流程配合。"
  "涉及人的研究在国内需要先拿伦理批件才能收数据，这与预注册的时间点常常冲突——务实的顺序是：方案定稿 → 伦理送审（同时）→ 预注册 → 拿到批件后开始收数据，注册文件里注明伦理审查状态。"
  "临床试验在中国有本国的注册平台，同时国际期刊通常认可世界卫生组织认证的一级注册平台；投国际刊前确认目标刊接受哪些平台 \`evidence: [T03-S009]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：CONSORT 与 SPIRIT 双双在 2025 年出新版，引旧版（CONSORT 2010 / SPIRIT 2013）是最省力的外行识别器 \`evidence: [T03-S003, T03-S004]\`；注册报告的接受刊数持续增加，且已从心理学扩散到生医、软件工程等领域 \`evidence: [T03-S027]\`；预注册模板本身在分化，按研究类型（定量实验 / 定性 / 二次数据 / 复制）选模板已经成为标准建议，用错模板会导致大量字段填「不适用」\`evidence: [T03-S030]\`。"
  "evidence: [T03-S027, T03-S029, T03-S030, T03-S003, T03-S004, T03-S005, T03-S006]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
