#!/usr/bin/env bash
# workflow-10.sh — 同行评审应对 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="同行评审应对 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-10.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-10.sh             # interactive
  ./workflow-10.sh --dry-run
  ./workflow-10.sh --json
  ./workflow-10.sh --explain
  ./workflow-10.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "同行评审应对 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**读懂决定信，先分类再动手**。交付物：一句话判断——小修 / 大修 / 拒稿但欢迎重投 / 拒稿 / 转投推荐。做完的标准：你知道「大修」意味着**还没决定**，「拒稿但鼓励重投」形式上**已经是拒稿**（重投通常按新稿处理），这两点是最常被误读的 \`evidence: [T03-S038]\`。"
  "**冷静期**。交付物：无。做完的标准：收到信的当天不回信、不改稿。"
  "**把所有意见拆成编号条目**。交付物：一张表——编号、原文（照抄）、类型（事实错误 / 方法质疑 / 解释分歧 / 表达问题 / 要求补实验）、你的处置（接受 / 部分接受 / 不接受）。做完的标准：一条不漏，包括编辑自己的意见。"
  "**先做能做的，再谈不能做的**。交付物：改好的稿件 + 变更标记版。做完的标准：所有表达与澄清类意见全部照做（这类占多数，且几乎没有争的价值）。"
  "**写逐条回复信**。交付物：结构固定——先一段总述（感谢 + 主要改动概览），然后逐条：审稿意见原文 → 我们的回应 → 具体改动位置（页码行号）。做完的标准：审稿人不用翻稿子就能看懂你改了什么。"
  "**不同意时的写法**。交付物：证据而不是态度——先复述对方的关切以证明你读懂了，再给出理由（数据、文献、方法学依据），最后说明你在稿中做了什么让读者也能看到这个权衡（例如在局限里加一段）。做完的标准：即使不接受意见，稿件也因此变好了一点。"
  "**提交前自查**。交付物：回复信与改稿一一对应、所有承诺的改动都真的做了、共同作者都看过。做完的标准：不存在「回复里说改了但稿子里没改」。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**各期刊自行规定的修回期限，差异极大且必须按目标刊的决定信为准**——常见的结构是小修给较短的期限、大修给较长的期限，很多刊允许申请延期。作者侧的实际投入：**社科 / 计算方向的小修**通常 3–7 个工作日；**大修**若不需补数据通常 2–4 周，需要补数据或补实验则由实验本身的周期决定，**生医方向补一组实验以月计并不罕见**。从修回到最终决定的时长同样由各刊自报口径决定，不可跨刊套用。"
  "**中国侧差异**:"
  "英语表达带来的额外损耗真实存在：相当一部分「表达不清」类意见其实是语言问题。语言润色可以用（很多出版商自己提供），但**内容不能代写**，且回复信必须由作者自己组织论证 \`evidence: [T03-S021]\`。"
  "国内考核的时间压力常导致「不敢大修、直接转投」，但转投等于放弃已经拿到的免费意见。务实做法是：即使决定转投，也先按意见改一遍。"
  "中文期刊的审稿文化与国际刊不同（意见更简短、更偏格式与规范、有时不给逐条理由），不要用应对国际刊的模板原样应对中文刊，反之亦然。"
  "「找关系打招呼」在国内的传说很多，但它落在期刊政策与国内规则的禁区里，且现代投稿系统的利益冲突申报会放大风险——这只作为要识别与避开的对象呈现 \`evidence: [T03-S021, T03-S013]\`。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：透明同行评审（公开评审意见与作者回复）在主要出版商的部分刊已成默认，回复信要按「将来可能被公开」来写 \`evidence: [T03-S084]\`；生成式模型进入评审两端，出版商相继明确——把未发表稿件上传到外部模型服务违反保密义务，审稿意见由模型代写也需披露或被禁止 \`evidence: [T03-S039, T03-S063]\`；论文工厂与批量造假的压力使编辑部增加了投稿前筛查（图像、引用、身份），作者侧的表现是：投稿后可能收到关于原始数据与身份核验的额外问询，这是常规流程而不是被怀疑 \`evidence: [T03-S041, T03-S037]\`。"
  "evidence: [T03-S038, T03-S014, T03-S013, T03-S063, T03-S084, T03-S021, T03-S039]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-10-walkthrough"
fi
