#!/usr/bin/env bash
# workflow-4.sh — 伦理审批与数据合规 (Decay risk: high) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="伦理审批与数据合规 (Decay risk: high)"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "伦理审批与数据合规 (Decay risk: high)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**判定适用哪几套规则**。交付物：一张勾选表——涉及人？涉及人体材料或人类遗传资源？涉及个人信息（是否敏感个人信息、是否未成年人）？涉及实验动物？涉及 AI 与算法？有境外合作方？有欧盟数据主体？做完的标准：每一项都有明确的是 / 否，且「是」项对应到具体条文。"
  "**确认审查主体与路径**。交付物：本单位科技伦理（审查）委员会的申请入口、受理时间表、所需材料清单。做完的标准：知道下一次受理截止日、知道要不要走专家复核。"
  "**准备材料包**。交付物：研究方案、知情同意书（含单独同意条款）、招募材料、数据管理与安全方案、研究者资质与培训证明、利益冲突声明。做完的标准：材料清单逐项打勾，无「稍后补」。"
  "**知情同意书按受试者读得懂的方式写**。交付物：一份同意书，开头是「关键信息」段——一个人为什么会愿意或不愿意参加。做完的标准：找一个非本专业的人读一遍能复述风险与退出方式 \`evidence: [T03-S035]\`。"
  "**个人信息的合法性基础单独过一遍**。交付物：一段说明——处理哪些个人信息、是否属敏感个人信息、同意是怎么取得的、如何最小化与去标识。做完的标准：即使伦理批件已到手，这段仍然独立成立 \`evidence: [T03-S019]\`。"
  "**提交、答复修改意见、拿批件**。交付物：批准文号 + 批准的方案版本号 + 有效期。做完的标准：文号、版本号、有效期三者一致，且论文方法学部分可以直接引用。"
  "**建立变更与续期机制**。交付物：一份记录，写明什么改动需要重新报批（方案实质性变更、增加人群、延长期限）。做完的标准：不会出现「实际做的和批的不是一回事」。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**中国高校 / 医院的本单位伦理委员会、涉及人的社科或临床研究**：材料准备 2–4 周；委员会通常按固定周期开会（常见为每月一次量级，各单位不同），从提交到出批件常见跨度为**数周到数月**，中间往往有一到两轮补充材料。**涉及人类遗传资源的国际合作审批 / 备案**是另一个量级，须按**数月**预留并列入关键路径 \`evidence: [T03-S018]\`。**动物实验的机构审查**在有成熟平台的单位通常比人体研究快。这些都是各单位自报的经验区间，跨单位差异极大，不要当成承诺值——正确做法是直接问本单位委员会秘书要历史平均处理时长。"
  "**中国侧差异**（这一节本身就是差异）:"
  "**审查触发范围更宽**：AI、算法与模型设计、个人数据处理被明确纳入，纯计算与社科二次数据研究在中国可能需要审查，而按美国联邦通则的豁免类别读英文攻略会误判 \`evidence: [T03-S016, T03-S035]\`。"
  "**人类遗传资源是中国独有的强监管环节**，英文攻略里没有对应制度 \`evidence: [T03-S018]\`。"
  "**同意的法律基础是两条线并行**：伦理审查 + 个人信息保护法的单独同意，只做前者不够 \`evidence: [T03-S019, T03-S017]\`。"
  "「IRB」这个词在中文语境里常被拿来泛指所有伦理委员会，但国内的科技伦理委员会与医学伦理委员会依据不同办法设立、职责范围不同，写论文时应写本单位委员会的正式名称与文号，不要直译成 IRB。"
  "**近期变化**: \`last_updated: 2026-09\`。主要变化集中在 2023 年那一波立法（科技伦理审查办法 2023-12-01 施行、人类遗传资源实施细则 2023-07-01 施行、涉及人的生命科学和医学研究伦理审查办法 2023-02-18 施行），此后各高校与医院在近 24 个月里陆续把这些要求落成本单位的实施细则与在线送审系统——**这意味着本单位流程比国家文件更新得更频繁，每次送审前都要重新看一遍本单位的现行版本**。同期国际侧的变化是数据共享要求收紧（资助机构把数据管理计划与共享作为拨款条件），伦理材料里的数据管理与安全方案权重上升 \`evidence: [T03-S025, T03-S026]\`。"
  "evidence: [T03-S016, T03-S017, T03-S018, T03-S019, T03-S020, T03-S035, T03-S036]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
