#!/usr/bin/env bash
# workflow-14.sh — 发表之后：归档、传播与被质疑的应对 (Decay risk: medium) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="发表之后：归档、传播与被质疑的应对 (Decay risk: medium)"

usage() {
  cat <<EOF
workflow-14.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-14.sh             # interactive
  ./workflow-14.sh --dry-run
  ./workflow-14.sh --json
  ./workflow-14.sh --explain
  ./workflow-14.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "发表之后：归档、传播与被质疑的应对 (Decay risk: medium)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**归档数据、代码与材料**。交付物：存入有持久标识符的仓储，拿到 DOI，写清元数据与使用许可；论文里的数据可用性声明指向这个 DOI。做完的标准：别人不联系你就能拿到并知道能怎么用 \`evidence: [T03-S045, T03-S044, T03-S048, T03-S034]\`。"
  "**满足公共获取要求**。交付物：按资助机构与所在单位的政策把论文存入指定仓储或本单位知识库。做完的标准：合规状态可查（资助机构侧的公共获取要求近年在收紧，须按当年版本）\`evidence: [T03-S060]\`。"
  "**让人找得到**。交付物：研究者唯一标识符与论文关联、机构主页更新、预印本版本与正式版本互相指向。做完的标准：搜你的名字能找到这篇，且各版本关系清楚 \`evidence: [T03-S085]\`。"
  "**写一段面向非专业读者的说明**。交付物：三到五句话——发现了什么、有多确定、不能推出什么。做完的标准：这段话可以直接给记者或做成社交媒体贴文，且不夸大。"
  "**准备好回答问询**。交付物：一份常见问题与答案（数据怎么拿、代码怎么跑、某个参数为什么这么选）。做完的标准：收到邮件当天能回。"
  "**监控被引与被质疑**。交付物：一个定期检查的动作——这篇被谁引了、引的时候是支持还是反驳；有没有出现在发表后评议平台上。做完的标准：不是靠别人转告才知道有人质疑 \`evidence: [T03-S077, T03-S078]\`。"
  "**被质疑时按事实回应**。交付物：一份可核验的回应（补充分析、原始数据、澄清说明），必要时联系编辑。做完的标准：区分「学术分歧」（公开讨论即可）与「可能的错误」（走工作流 13）。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**作者侧的投入，不含期刊排版与见刊周期**：归档整理（数据 + 代码 + README + 元数据）在流程规范的项目里 **2–5 天**，在没有提前规划的项目里可能要 **2–4 周**（这就是提前做的价值）；通俗说明 1–2 小时；被引与质疑的监控是每季度 30 分钟量级的常规动作。**从接受到正式见刊**的时长由各刊自报口径决定，差异极大，不可跨刊套用。"
  "**中国侧差异**:"
  "**数据出境是硬约束**：国际通用仓储不是默认可选项，涉及人类遗传资源信息的须先走事先报告与信息备份 \`evidence: [T03-S018]\`。务实做法是分层归档——可公开的挂国际仓储，受限的放境内受控访问，两层都在数据可用性声明里写清。"
  "机构知识库在国内普及度不均，很多单位没有长期可维护的存储；把归档位置写成个人网盘是常见但不可持续的做法。"
  "**期刊分级的国内口径正在变**：中科院文献情报中心已停止更新与发布分区表（2026-03-27 声明），过渡期内各单位口径不一，做年度总结与申请材料时必须写清用的是哪一套、哪一年，不能只写「几区」\`evidence: [T03-S056, T03-S057]\`。"
  "传播侧：国内的科研传播渠道与英文攻略假设的不同，但纪律是一样的——不夸大、不把相关说成因果、不用单篇论文的结论去支持超出其范围的主张。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：撤稿与更正数据进入公开元数据接口并每工作日更新，「引用前查撤稿」从愿望变成可执行动作 \`evidence: [T03-S075, T03-S086]\`；公共获取政策在收紧（资助机构侧取消延迟期一类的变化），发表后的合规动作变多 \`evidence: [T03-S060]\`；国内期刊分级口径因分区表停更进入过渡期，个人成果呈现方式需要相应调整 \`evidence: [T03-S056]\`。"
  "evidence: [T03-S045, T03-S034, T03-S018, T03-S060, T03-S075, T03-S086, T03-S056, T03-S077, T03-S028]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-14-walkthrough"
fi
