#!/usr/bin/env bash
# workflow-7.sh — 图表与结果呈现 (Decay risk: low) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="图表与结果呈现 (Decay risk: low)"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "图表与结果呈现 (Decay risk: low)" 工作流。

入门 SOP 共 7 步, 失败模式自检 7 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先写图注再画图**。交付物：每张图一句话——这张图要让读者相信什么。做完的标准：一张图只讲一件事，讲两件事就拆成两张。"
  "**选对图形**。交付物：图形类型的选择理由（比较用什么、分布用什么、关系用什么、随时间变化用什么）。做完的标准：不用条形图去表达分布——尽量展示原始数据点或分布形状，而不只是均值加误差棒。"
  "**把不确定性画出来**。交付物：区间、分布或数据点。做完的标准：读者能看出结论有多确定，而不只是看出哪根柱子高。"
  "**可及性检查**。交付物：色觉障碍模拟检查通过 + 不依赖颜色单独编码信息（同时用形状、线型、直接标注）。做完的标准：图印成灰度仍然读得懂 \`evidence: [T03-S042, T03-S049]\`。"
  "**按目标刊的规格出图**。交付物：符合尺寸、分辨率、字号、字体、文件格式要求的图文件。做完的标准：不用编辑部返工。"
  "**图像完整性自查**（尤其涉及显微、电泳、影像类图像）。交付物：原始未处理图像存档 + 一份处理记录（做了什么调整、是否全图统一）。做完的标准：任何调整都作用于整幅图、不改变原始数据的含义，且原图随时可提供 \`evidence: [T03-S041]\`。"
  "**给别人看一次**。交付物：一位非本方向的同行看图 30 秒后的复述。做完的标准：他复述的就是你写的那句图注。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**一篇实证论文（社科或计算方向）的 4–6 张主图**：从有结果到出第一版图 3–7 天；打磨到投稿质量再 3–5 天；按审稿意见改图每轮 1–3 天。**生医论文中含显微 / 电泳 / 影像类图版（figure panel）的**，因为要回原始文件核对与排版，通常比上面多一倍时间。这些是常见经验区间不是标准。"
  "**中国侧差异**:"
  "国内有成熟的图表代做与「润色美化」服务市场，其中大量服务处在从排版协助到实质性代做的连续谱上。边界很清楚：排版与美工协助可以，但**不得改变数据所表达的内容**；由他人代为编造或修饰实验图像属于明确的科研失信行为 \`evidence: [T03-S021, T03-S041]\`。"
  "中文期刊对图的格式要求与国际刊差异较大（字体、单位写法、图注位置），一稿两投两种格式是常态，用脚本出图能显著降低这部分成本。"
  "汇报与答辩场景对「图要好看」的要求在国内更强，但答辩用图与论文用图的标准不同——答辩图可以简化，论文图不能。"
  "**近期变化**: \`last_updated: 2026-09\`。两条：图像筛查已从「有人举报才查」变成常规化——主要出版商对随机抽取的论文做图像抽查，投稿前自查图像完整性已经是标准动作 \`evidence: [T03-S041]\`；生成式模型能生成看起来像实验图的图像，出版商相应收紧了对原始文件的索取与 AI 生成内容的披露要求，涉及科研数据的图像一般不允许由生成式模型产生 \`evidence: [T03-S039, T03-S010]\`。"
  "evidence: [T03-S041, T03-S042, T03-S049, T03-S003, T03-S002, T03-S021]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
