#!/usr/bin/env bash
# workflow-8.sh — 论文写作 (Decay risk: low) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="论文写作 (Decay risk: low)"

usage() {
  cat <<EOF
workflow-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-8.sh             # interactive
  ./workflow-8.sh --dry-run
  ./workflow-8.sh --json
  ./workflow-8.sh --explain
  ./workflow-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "论文写作 (Decay risk: low)" 工作流。

入门 SOP 共 8 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先定一句话结论与一个目标刊**。交付物：一句话（本文发现了什么）+ 一个目标刊 + 该刊的作者指南与字数限制。做完的标准：这句话就是将来的标题内容，且符合目标刊的体裁。"
  "**搭骨架：图先于文**。交付物：主图顺序 + 每张图一句话 + 每个小节的主题句列表。做完的标准：只读主题句就能读懂全文逻辑 \`evidence: [T03-S051]\`。"
  "**先写方法**（最容易写、也最不受心情影响）。交付物：详细到能被重做的方法学部分。做完的标准：对照目标研究类型的报告规范清单逐条打勾——随机对照试验对 CONSORT 2025，观察性研究对 STROBE，动物实验对 ARRIVE 2.0，定性研究对 COREQ 或 SRQR，系统综述对 PRISMA 2020 \`evidence: [T03-S003, T03-S005, T03-S006, T03-S007, T03-S008, T03-S002]\`。"
  "**写结果**：只描述，不解释。交付物：按图顺序组织的结果段落，每段一个发现，报告效应量与不确定性。做完的标准：没有「证明」「说明了」这类解释词。"
  "**写引言的漏斗**：从这个领域为什么重要 → 已知什么 → 缺什么 → 本文做什么。交付物：通常 3–5 段。做完的标准：最后一段与你的一句话结论对得上，且中间没有跳步。"
  "**写讨论**：主要发现 → 与已有工作的关系 → 机制或解释 → **局限** → 意义与下一步。交付物：讨论部分。做完的标准：局限一节写的是真正会削弱结论的东西，不是「样本量还可以更大」这种套话。"
  "**最后写标题与摘要**。交付物：标题、摘要、关键词。做完的标准：摘要能独立成立，且摘要里的每个数字都能在正文找到出处。"
  "**自查与外审**。交付物：报告规范清单对照表、参考文献核对、共同作者的书面确认。做完的标准：每一条参考文献都被真正读过、每个作者都看过并同意这一版。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**社科 / 计算方向、数据已就绪的一篇实证论文**：骨架 3–5 天，方法 1 周，结果 1–2 周，引言 1 周，讨论 1–2 周，标题摘要与自查 3–5 天，合作者回稿等待另计——**首篇论文的作者通常是这个区间的两到三倍**。**生医实验论文**常因补实验而反复中断，不适合按连续工时估。**学位论文改写成期刊论文**主要工作量在删（学位论文的文献综述与方法细节需要压缩到期刊体量），通常 2–6 周。这些都是经验区间，不是任何机构的口径。"
  "**中国侧差异**:"
  "英语写作本身是额外成本。**语言润色是允许的、也是被广泛接受的**（很多出版商自己提供），但边界很清楚：润色不得改变学术内容，且不得由他人代写实质内容——代写在中国是明文列举的科研失信行为 \`evidence: [T03-S021]\`。"
  "学位论文与期刊论文在国内是两套评价体系：学位论文有抽检制度、有格式与查重的硬性要求，期刊论文按目标刊的作者指南。两者的写法差异比英文攻略里描述的更大，不要指望一稿两用。"
  "「一稿多投」在中国语境里包含中英文双语重复发表这一常见情形，它在期刊政策与国内规则里都属于禁止行为；如果确有翻译发表的需要，必须两边编辑都事先知情并同意、并注明出处 \`evidence: [T03-S021, T03-S013]\`。"
  "国内不少课题组用中文写初稿再翻译，这条路的风险在于中英文的论证结构不同（中文习惯先铺垫后结论，英文期刊要求先给结论），翻译出来的文章常被审稿人评为「结构松散」。务实做法是骨架直接用英文的主题句写。"
  "**近期变化**: \`last_updated: 2026-09\`。两条：AI 写作辅助从灰色地带变成有明确规则的领域——ICMJE 2026 年 1 月版把 AI 单独成节，主要出版商的编辑政策统一要求披露使用方式且**不得把 AI 列为作者**（AI 无法承担作者责任）\`evidence: [T03-S010, T03-S039]\`；报告规范在 2025 年集中换版（CONSORT 2025、SPIRIT 2025），写作前必须去规范总登记处确认当前版本号 \`evidence: [T03-S001, T03-S003, T03-S004]\`。"
  "evidence: [T03-S011, T03-S012, T03-S010, T03-S009, T03-S001, T03-S003, T03-S021, T03-S013]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-8-walkthrough"
fi
