#!/usr/bin/env bash
# workflow-9.sh — 期刊选择与投稿 (Decay risk: high) SOP walkthrough for 科研方法与论文发表.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="科研方法与论文发表"
WORKFLOW="期刊选择与投稿 (Decay risk: high)"

usage() {
  cat <<EOF
workflow-9.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-9.sh             # interactive
  ./workflow-9.sh --dry-run
  ./workflow-9.sh --json
  ./workflow-9.sh --explain
  ./workflow-9.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "期刊选择与投稿 (Decay risk: high)" 工作流。

入门 SOP 共 7 步, 失败模式自检 8 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**列 3–5 本候选刊并核对范围**。交付物：候选表，每本写清体裁（原创研究 / 短报告 / 综述）、字数限制、读者是谁、近两年有没有发过同类工作。做完的标准：能指出每本刊上最近一篇与你最像的论文。"
  "**做可信度自查**。交付物：对每本候选刊逐项打勾——出版商与编委会信息是否可查、同行评审流程是否写明、是否被你认可的索引或目录收录、费用是否在投稿前明示、联系方式是否真实。用投稿前核查清单与开放获取期刊目录的收录判据作为工具 \`evidence: [T03-S053, T03-S031, T03-S032, T03-S054]\`。做完的标准：任何一项存疑就不投。"
  "**决定预印本要不要先挂**。交付物：一个决定 + 目标刊对预印本的政策截图或链接。做完的标准：确认目标刊接受已发预印本的稿件（多数接受，但少数刊与少数学科不接受），并知道挂出后怎么更新版本 \`evidence: [T03-S085]\`。"
  "**确定署名顺序与贡献声明**。交付物：作者名单与顺序（全体书面确认）+ 贡献声明（用贡献者角色分类法逐人逐项）+ 通讯作者 + 利益冲突声明。做完的标准：每位作者都满足署名四条标准，不满足的移入致谢 \`evidence: [T03-S011, T03-S012]\`。"
  "**按目标刊格式改稿**。交付物：符合该刊作者指南的正文、图、参考文献格式 + 必需的清单与声明（报告规范清单、数据可用性声明、伦理批件号、注册号、AI 使用披露）。做完的标准：投稿系统的必填项都有对应材料 \`evidence: [T03-S039, T03-S010]\`。"
  "**写投稿信**。交付物：一页——本文做了什么、为什么适合这本刊、有什么新意、声明未一稿多投与未重复发表、（可选）推荐或回避的审稿人及理由。做完的标准：编辑只读这一页就能判断要不要送审。"
  "**提交并记录**。交付物：投稿日期、稿号、系统里的状态。做完的标准：有一份自己的投稿台账，能回答「这篇现在在哪、投了多久」。"
)
declare -a FAILURE_MODES=(
  "**时间尺度**: 口径为**期刊自报或作者社群经验，且各刊差异极大，不可合并成单一数字**。可以确定的结构性事实是：桌拒通常最快（以天计），送审后到第一次决定的时长由各刊自报的中位数决定、**同一学科内不同刊可以相差数倍**，从投稿到最终接受再到见刊还要加上修回轮次与排版。**正确做法**是去目标刊官网查它自报的处理时长指标（很多刊会公布中位审稿天数），并注意这是该刊自报的口径，不等于你的稿件的实际经历，也不能跨刊跨学科套用。任何「某学科平均审稿 X 个月」的说法都要问清是哪一年、哪个数据源、哪些刊、是中位数还是均值。"
  "**中国侧差异**:"
  "**分区表这件事变了**：中国科学院文献情报中心已发布官方声明停止更新与发布《期刊分区表》（2026-03-27 声明）。这意味着「几区」这个在国内考核与奖励里被大量使用的口径失去了持续更新的来源，各单位在改用其他判据的过渡期里口径会更不一致——写材料时必须写清用的是哪一套、哪一年 \`evidence: [T03-S056]\`。"
  "影响因子是**期刊**的属性不是单篇论文的属性；用期刊指标替代单篇质量与人事决定，正是研究评价宣言反对的做法，中国官方版的对应文件是 2020 年破除「唯论文」的两份文件（代表作评价、禁止与奖金直接挂钩）\`evidence: [T03-S057, T03-S058, T03-S022]\`。"
  "国内有专门的《国际期刊预警名单》发布平台，用途是提示风险而不是给出「是否掠夺性」的判定；不要把「不在预警名单上」当作安全证明 \`evidence: [T03-S040]\`。"
  "「投中文刊还是英文刊」在国内是一个真实的策略问题而不是能力问题：中文刊在部分学科的评价体系里权重正在上升，但两者的审稿文化、格式要求、周期都不同，不要用同一套预期。"
  "**近期变化**: \`last_updated: 2026-09\`。三条：一是中科院分区表停更（2026-03 官方声明），期刊分级的国内口径进入过渡期 \`evidence: [T03-S056]\`；二是开放获取政策收紧——资助机构侧的公共获取要求在推进（如取消延迟期一类的变化），投稿前要同时看目标刊政策与自己资助机构的要求 \`evidence: [T03-S060]\`；三是 AI 披露从建议变成投稿系统的必填项，ICMJE 2026 年 1 月版把 AI 独立成节 \`evidence: [T03-S010, T03-S062]\`。"
  "evidence: [T03-S053, T03-S031, T03-S032, T03-S055, T03-S056, T03-S057, T03-S058, T03-S011, T03-S012, T03-S061]"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-9-walkthrough"
fi
