#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for 亚马逊管理之道.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="亚马逊管理之道"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果 动手造之前先写 PR/FAQ，写不清楚新闻稿 = 还没想清楚，别造 → 则 ：working backwards。案例：一个新功能立项，先写「发布那天的客户新闻稿 + FAQ」，写的过程中发现「客
  • 如果 重要的会用 6-pager + 前 20 分钟静默阅读，禁 PPT → 则 ：读不下去的备忘录 = 想不清楚的方案。案例：季度评审发一份 6 页叙事文，全场先默读再逐段问，比 40 页 PPT 更
  • 如果 招人必过 Bar Raiser，缺人也不降标准 → 则 ：跨组、不评自己组、一票否决但不能强推。案例：某组急着补人想放水，Bar Raiser 在 debrief 上否掉「他只
  • 如果 事故后先止血再 COE + 5 Whys，根因必须挖到系统/机制，禁止停在「人为失误」 → 则 ：blameless。案例：一次线上故障，5 Whys 从「工程师手滑」一路问到「部署流程缺护栏」，行动项是给流程加护栏
  • 如果 充分辩论后 disagree and commit；但上级也要对下级 commit，别把它当闭嘴令 → 则 ：案例：贝索斯对某剧集持保留但说「我不同意，但我们赌一把，我不挡路」——双向适用；反例是领导跳过辩论直接甩「别吵了 co
  • 如果 年度规划自上而下给方向 + 自下而上写 OP1，挑约 15% 成 S-Team goals(刻意激进，预期只完成约 75 → 则 ：案例：OP1 评审里 S-Team 从各组指标挑出约 15% 全公司最重要的目标，由 Finance 中央打红黄绿灯，

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "动手造之前先写 PR/FAQ，写不清楚新闻稿 = 还没想清楚，别造"
  "重要的会用 6-pager + 前 20 分钟静默阅读，禁 PPT"
  "招人必过 Bar Raiser，缺人也不降标准"
  "事故后先止血再 COE + 5 Whys，根因必须挖到系统/机制，禁止停在「人为失误」"
  "充分辩论后 disagree and commit；但上级也要对下级 commit，别把它当闭嘴令"
  "年度规划自上而下给方向 + 自下而上写 OP1，挑约 15% 成 S-Team goals(刻意激进，预期只完成约 75%)"
)
declare -a RULE_ACTIONS=(
  "：working backwards。案例：一个新功能立项，先写「发布那天的客户新闻稿 + FAQ」，写的过程中发现「客户为什么要用」答不上来 → 砍掉，省下几个月工程。evidence: [T03-S001, T02-S002]"
  "：读不下去的备忘录 = 想不清楚的方案。案例：季度评审发一份 6 页叙事文，全场先默读再逐段问，比 40 页 PPT 更快逼出逻辑漏洞。evidence: [T03-S002, T02-S003]"
  "：跨组、不评自己组、一票否决但不能强推。案例：某组急着补人想放水，Bar Raiser 在 debrief 上否掉「他只是最近两周里最好的一个」这种 desperation hire。evidence: [T03-S004, T02-S009]"
  "：blameless。案例：一次线上故障，5 Whys 从「工程师手滑」一路问到「部署流程缺护栏」，行动项是给流程加护栏而非罚人。evidence: [T03-S006, T06-S014]"
  "：案例：贝索斯对某剧集持保留但说「我不同意，但我们赌一把，我不挡路」——双向适用；反例是领导跳过辩论直接甩「别吵了 commit」压制异见。evidence: [T02-S015, T06-S012]"
  "：案例：OP1 评审里 S-Team 从各组指标挑出约 15% 全公司最重要的目标，由 Finance 中央打红黄绿灯，若全部 100% 达成说明目标定太保守。evidence: [T03-S005, T02-S008]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
