#!/usr/bin/env bash
# type.sh — Type 决策助手 for 亚马逊管理之道.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="亚马逊管理之道"
TOPIC="Type"

usage() {
  cat <<EOF
type.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./type.sh             # interactive
  ./type.sh --dry-run   # walk through but no file
  ./type.sh --json      # JSON to stdout
  ./type.sh --explain   # show backing playbook rules + mental models
  ./type.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Type 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 决策先问「这是几号门」：Type 2 可逆→授权个人快决(约 70% 信息就动)，Type 1 不可逆→慢而多咨询 → 则 ：出自 2015 信。案例：改个页面文案是双向门，让一线快试快回；建一个新数据中心是单向门，上 6-pager + 多方

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "决策先问「这是几号门」：Type 2 可逆→授权个人快决(约 70% 信息就动)，Type 1 不可逆→慢而多咨询"
)
declare -a RULE_ACTIONS=(
  "：出自 2015 信。案例：改个页面文案是双向门，让一线快试快回；建一个新数据中心是单向门，上 6-pager + 多方评审。evidence: [T02-S012, T04-S001]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "type-decision"
fi
