#!/usr/bin/env bash
# topic-1.sh — 考核 决策助手 for 广告外包公司绩效管理.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="广告外包公司绩效管理"
TOPIC="考核"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 考核 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 创意岗用「质量软评+效率结果硬指标」，别把创意塞进 KPI 数字 → 则 ：三层分治。案例：创意总监考核＝作品获奖/评议(质量,软,占比)+ 提案通过率/返稿次数(效率,硬)+ 项目利润/客户续
  • 如果 考核走 PBC/军令状 → 过程辅导 → 述职 → 校准会 → 面谈(GROW) → 结果应用 → 则 ：闭环。案例：季度 PBC 定目标(业绩+团队+个人成长)，季末自评述职→跨组校准会拉齐标准→GROW 教练式面谈，避免
  • 如果 把甲方不确定性纳入指标 + 用合同前置对冲，别只靠事后考核硬扛 → 则 ：乙方特殊。案例：把改稿次数、回款周期纳入项目绩效，同时 SOW 写明「超 N 轮改稿加价」，从源头对冲无限改稿，而非只

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "创意岗用「质量软评+效率结果硬指标」，别把创意塞进 KPI 数字"
  "考核走 PBC/军令状 → 过程辅导 → 述职 → 校准会 → 面谈(GROW) → 结果应用"
  "把甲方不确定性纳入指标 + 用合同前置对冲，别只靠事后考核硬扛"
)
declare -a RULE_ACTIONS=(
  "：三层分治。案例：创意总监考核＝作品获奖/评议(质量,软,占比)+ 提案通过率/返稿次数(效率,硬)+ 项目利润/客户续约(结果,硬)，而非「每月出 N 个 idea」。evidence: [T04-S001, T01-S002]"
  "：闭环。案例：季度 PBC 定目标(业绩+团队+个人成长)，季末自评述职→跨组校准会拉齐标准→GROW 教练式面谈，避免主管各打各分。evidence: [T03-S005, T01-S007]"
  "：乙方特殊。案例：把改稿次数、回款周期纳入项目绩效，同时 SOW 写明「超 N 轮改稿加价」，从源头对冲无限改稿，而非只扣团队奖金。evidence: [T01-S004, T03-S001]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
