#!/usr/bin/env bash
# topic-3.sh — 工时 决策助手 for 广告外包公司绩效管理.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="广告外包公司绩效管理"
TOPIC="工时"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 工时 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 先定位/定价，再定考核口径（不可倒装） → 则 ：定价方式决定绩效指标(工时制→考 utilization；价值/成果制→考项目毛利/客户价值)。案例：一家小热店从计时
  • 如果 utilization 目标 agency 定 ~60%，别照搬律所 70-80%(律所口径) → 则 ：压太高逼过劳/造假工时。案例：照搬咨询 80%(律所/咨询口径) 目标，团队把非计费工时(学习/比稿/内部)硬塞进项目
  • 如果 AIGC 后降纯工时/产出量权重，转单位价值/结果 → 则 ：计费工时悖论。案例：AI 让设计产能翻倍、客户要「AI 折扣」，把设计考核从「出图量/工时」改「单位交付价值+客户复购

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "先定位/定价，再定考核口径（不可倒装）"
  "utilization 目标 agency 定 ~60%，别照搬律所 70-80%(律所口径)"
  "AIGC 后降纯工时/产出量权重，转单位价值/结果"
)
declare -a RULE_ACTIONS=(
  "：定价方式决定绩效指标(工时制→考 utilization；价值/成果制→考项目毛利/客户价值)。案例：一家小热店从计时报价转 value-based pricing(Enns)，考核口径同步从「计费工时」改「项目毛利率」，否则销售拼命压工时却毁利润。evidence: [T03-S001, T01-S004]"
  "：压太高逼过劳/造假工时。案例：照搬咨询 80%(律所/咨询口径) 目标，团队把非计费工时(学习/比稿/内部)硬塞进项目工时表，数据失真+过劳流失。evidence: [T01-S001, T06-S003]"
  "：计费工时悖论。案例：AI 让设计产能翻倍、客户要「AI 折扣」，把设计考核从「出图量/工时」改「单位交付价值+客户复购」，否则产能越高绩效数字越难看。evidence: [T02-S001, T01-S001]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
