#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 亚马逊管理之道.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="亚马逊管理之道"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 决策可逆性判定（Type 1 / Type 2）
  9.2 客户与 Working Backwards
  9.3 输入指标设计
  9.4 机制 vs 良好意图
  9.5 组织与所有权
  9.6 迁移边界与文化风险

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "决策可逆性判定（Type 1 / Type 2）"
  "客户与 Working Backwards"
  "输入指标设计"
  "机制 vs 良好意图"
  "组织与所有权"
  "迁移边界与文化风险"
)
declare -a DIM_QUESTIONS=(
  "这个决策是单向门(不可逆/重后果)还是双向门(可逆/可改)？——决定该快授权还是慢评审。"
  "客户是谁、现在怎么解决、我们凭什么更好、最可能失败的 3 个原因——能不能写出让客户兴奋的 PR/FAQ。"
  "真正驱动你要的 output 的**可控输入指标**是哪几个(而非考核滞后 output)。"
  "你要改的是「反复出现的行为」吗？如果是，该装什么带 inspection 闭环的机制(谁查/多久/怎么闭环)，而不是发倡议。"
  "这件事有没有一个全职 single-threaded owner？他对别组有哪些硬依赖需要拆？"
  "把这套机制搬到你的情境(规模/行业/团队)有没有 cargo-culting 风险？会不会带上 URA/高压式阴暗面？"
)
declare -a DIM_SOURCES=(
  "Track 02 决策机制(Type1/Type2) + Track 04 贝索斯 2015 信。"
  "Track 03 working backwards SOP + Track 02 PR/FAQ 机制。"
  "Track 02 input/output metrics + Track 03 WBR SOP(Cedric Chin 拆解)。"
  "Track 02 机制清单(WBR/COE/Bar Raiser/Andon) + Track 01 元原则。"
  "Track 02 two-pizza→STL + Track 03 组织设计。"
  "Track 01 争议节(机制可迁移之争 + 文化批判) + Track 02 避坑清单。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "门的类型 + 对应流程(Type2 授权个人约 70% 信息就动 / Type1 上 6-pager 多方评审)。"
  "一页 PR/FAQ 草稿 + go/no-go 判断(客户会不会兴奋)。"
  "2-4 个可控输入指标 + 它们如何驱动 output + WBR 看板排法(input 在前)。"
  "机制设计(触发→动作→inspection→闭环) + 谁是 inspector。"
  "single-threaded owner 人选 + 依赖清单 + 拆依赖方案。"
  "迁移前提是否满足 + 需要裁剪/放弃的机制 + 文化风险提示。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
