#!/usr/bin/env bash
# topic-5.sh — —— 决策助手 for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
TOPIC="——"

usage() {
  cat <<EOF
topic-5.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-5.sh             # interactive
  ./topic-5.sh --dry-run   # walk through but no file
  ./topic-5.sh --json      # JSON to stdout
  ./topic-5.sh --explain   # show backing playbook rules + mental models
  ./topic-5.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 一个「成功」里有人碰过——扶一把、遥操作、重摆、重启 → 则 它不计入自主成功率，只计入带兜底完成率，两个数字分开报。*案例*：这是本行最大的一笔糊涂账；它是资深人的自律规则与集成商

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个「成功」里有人碰过——扶一把、遥操作、重摆、重启"
)
declare -a RULE_ACTIONS=(
  "它不计入自主成功率，只计入带兜底完成率，两个数字分开报。*案例*：这是本行最大的一笔糊涂账；它是资深人的自律规则与集成商的验收实践，没有任何标准或政策明文要求这个拆分——2026-06-03 工信部与国资委的实景实训专项只要求出具含「作业成功率、效率提升率、安全可靠性、经济可行性」四项的评估报告。干预率的口径定义见 \`references/research/06-glossary.md\` G9 术语条"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-5-decision"
fi
