#!/usr/bin/env bash
# topic-2.sh — 案例 决策助手 for 机器人与具身智能.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="机器人与具身智能"
TOPIC="案例"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 5 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 案例 主题下的 playbook 规则组合成交互树。

基于 5 条规则:
  • 如果 任务的主要难点是来料位置或姿态不确定 → 则 先算「改工装 / 改来料呈现」的成本，再算机器人方案的成本，两者并列给决策方，不要直接上视觉。*案例*：集成项目失败的公
  • 如果 规格书写着 ±0.02 mm → 则 默认它是重复定位精度，绝对精度按毫米级估，并追问是按 ISO 9283 在什么负载与速度下测的。*案例*：这是本行最高频
  • 如果 要求亚毫米级装配而机器人绝对精度只有毫米级 → 则 改走相对定位路线（在作业点用视觉或力控二次找正），不要靠加标定次数硬补。*案例*：手眼标定残差看着很小却换个工作区域就偏
  • 如果 要在人机共享空间作业 → 则 按这个具体应用做风险评估并实测力/压强或停止距离，「先把速度调高看看能不能过节拍」是红线不是选项。*案例*：ISO/TS
  • 如果 产品品类频繁更换（每天或每周换一次） → 则 成本模型的主项是换型时间与首件合格时间，不是单次任务成功率；验收条款里必须有换型条款，否则这笔账在上线后才会出现。*案例

相关心智模型:
  • 先问分母，再看数字: 这一行的每个性能数字只在它的口径里成立——几个任务 × 几次试验、真机还是仿真、是否新物体新场景、有没有人接管或重试、谁做的验证；分母没给出来，这个数字就不含信息。
  • 先改机械，再改算法: 能用工装、来料呈现方式或本体选型结构化掉的问题，不要用感知与策略去解；而且本体一旦定下来，可行的控制与学习方法集合就已经被定死了大半。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "任务的主要难点是来料位置或姿态不确定"
  "规格书写着 ±0.02 mm"
  "要求亚毫米级装配而机器人绝对精度只有毫米级"
  "要在人机共享空间作业"
  "产品品类频繁更换（每天或每周换一次）"
)
declare -a RULE_ACTIONS=(
  "先算「改工装 / 改来料呈现」的成本，再算机器人方案的成本，两者并列给决策方，不要直接上视觉。*案例*：集成项目失败的公开归因集中在零件变异、工装不良与需求不清，而不是机器人硬件不行"
  "默认它是重复定位精度，绝对精度按毫米级估，并追问是按 ISO 9283 在什么负载与速度下测的。*案例*：这是本行最高频的外行破绽，规格书标的几乎总是 repeatability，两者可差一到两个数量级"
  "改走相对定位路线（在作业点用视觉或力控二次找正），不要靠加标定次数硬补。*案例*：手眼标定残差看着很小却换个工作区域就偏，问题在位姿分布而不是样本数，重采覆盖实际作业区的位姿才有用"
  "按这个具体应用做风险评估并实测力/压强或停止距离，「先把速度调高看看能不能过节拍」是红线不是选项。*案例*：ISO/TS 15066 的协作要求已并入 ISO 10218-2:2025，测试仍要做但引用依据变了，合同与报告模板需同步更新"
  "成本模型的主项是换型时间与首件合格时间，不是单次任务成功率；验收条款里必须有换型条款，否则这笔账在上线后才会出现。*案例*：资深人在验收清单里把「连续运行 + 换型 + 异常恢复」三类非单次任务条款列为必须项，缺这三条的验收标准会被 demo 骗"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
