#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 谈判与议价.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="谈判与议价"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 先定坐标：谁在谈、代表谁、这是哪一类交易
  9.2 先算结构，再想话术
  9.3 把替代方案与保留价算成数字
  9.4 把单议题拆成多议题，并给议题赋权重
  9.5 核对数字的口径、来源等级与版本
  9.6 查合规坐标：法域、动作、时效
  9.7 判断流派前提是否成立，再决定用谁的招

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定坐标：谁在谈、代表谁、这是哪一类交易"
  "先算结构，再想话术"
  "把替代方案与保留价算成数字"
  "把单议题拆成多议题，并给议题赋权重"
  "核对数字的口径、来源等级与版本"
  "查合规坐标：法域、动作、时效"
  "判断流派前提是否成立，再决定用谁的招"
)
declare -a DIM_QUESTIONS=(
  "我方与对方各是谁、双方是本人还是代理人、标的是什么、这是一次性还是长期关系、准据法与法域在哪、时间压力在谁那边。"
  "这场谈判赢在信息、赢在替代方案，还是赢在流程设计；对应该上哪一层工具。"
  "同类交易的可比成交价、切换成本、时间成本、谈崩走争议解决要花多少钱多久；以及对方的替代方案。"
  "除了价格还能谈什么——量、期限、账期、交付节奏、验收标准、责任上限、排他、知识产权归属、续约与调价机制、退出条款、SLA、培训与备件，目标是拆出至少五个变量。"
  "任何要写进方案的百分比、效应量或基准，先答三问——分母是什么、有没有对照组、这是元分析 / 单项实验 / 科普综述 / 还是厂商自报；结论出自哪一年哪一版。"
  "逐个动作对红线——录音、送礼与款待、虚构竞标者、伪造授权、竞争者之间谈价格、买方组织多家供应商谈统一价、账期上限、薪酬史提问。每条写清法域、条号与生效日，**已公布未生效的要单独标出来**。"
  "这个场景的时间跨度与依赖结构，决定战术共情、原则式、实战议价三套动作各自还成不成立。"
)
declare -a DIM_SOURCES=(
  "对方组织的公开信息与决策链 > 合同里的「适用法律」与「争议解决」两条 > \`references/research/03-workflows.md\` 的「立项与利益相关方梳理」。"
  "\`references/research/02-tools.md\` 的选型决策树 > \`references/research/03-workflows.md\` 的「准备与对手画像」「替代方案与保留价」两节。"
  "官方统计（国家统计局 PPI、美国劳工统计局）> 争议解决机构的规则与收费表（CIETAC / SIAC / HKIAC）> 行业协会的年度条款调查 > 自报型平台数据（只当锚点，不当引用依据）；流程见 \`references/research/03-workflows.md\` §3，术语见 \`references/research/06-glossary.md\` 的 BATNA / 保留价 / ZOPA 词条。"
  "\`references/research/02-tools.md\` 必备层第 3、4、5 项（打分表 / 交换矩阵 / MESO）> \`references/research/04-canon.md\` 的 MESO 与谈判者困境条目。"
  "\`references/research/04-canon.md\` 第 9 节「争议与被推翻的说法」> \`references/research/02-tools.md\` 新兴层与避坑清单里的厂商数字警告。"
  "\`references/research/06-glossary.md\` §3 法规与合规（§3.1 中国 / §3.2 美国与国际 / §3.3 最近 18 个月的新变化）> \`references/research/03-workflows.md\` 的「开局」与「合同化与争议解决条款」两节；一律读法规原文与官方执法口径，不读汇总榜单和厂商合规博客。"
  "\`references/research/01-figures.md\` 的流派分歧与「逐字原话候选」> \`references/research/04-canon.md\` 的争议节。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话坐标——「这是一场 {一次性/有限次/长期} 的 {交易类型} 谈判，准据法是 {X}，对方拍板的人是 {Y}」。"
  "三选一的判断 + 这一叉对应的两三件准备动作；判断「赢在信息 / 赢在替代方案」时只用纸笔层，不要推荐软件。"
  "四个数（我的保留价、目标价、我猜对方的保留价、这个猜测的依据）+ 一张非价格退出条件清单（责任无上限、单方变更权、无法审计的计价口径、超出合规红线的付款安排）。"
  "一张 100 分制的议题打分表（**把你自己的 BATNA 也当成一个方案用同一张表打分，算出来的那个分就是保留价**）+ 反推的对方打分表 + 2-3 个对你等值、结构不同的报价包。"
  "每个被引用的数字后面挂一个来源等级标签；凡是厂商或培训方自报的，逐字写「自报，无第三方审计」。"
  "一句「在 {法域}，{动作} 的边界是 {规则}，依据是 {条号}，核对日 {日期}」；同时给出合规路径而不只是禁令。"
  "先给场景打标签，再选工具箱；呈现流派分歧时写清是谁在批评谁、有没有回应，不要把单向开火写成双方辩论。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
