#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 企业财务与 CFO 视角.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="企业财务与 CFO 视角"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 先定场景坐标：这是哪一层的问题
  9.2 分清利润问题还是现金问题
  9.3 核对数字的口径与时效
  9.4 判断该用哪套成本语言
  9.5 如果涉及融资或股权：先算瀑布再谈估值
  9.6 核对流派前提是否成立
  9.7 查合规与时效变量

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "先定场景坐标：这是哪一层的问题"
  "分清利润问题还是现金问题"
  "核对数字的口径与时效"
  "判断该用哪套成本语言"
  "如果涉及融资或股权：先算瀑布再谈估值"
  "核对流派前提是否成立"
  "查合规与时效变量"
)
declare -a DIM_QUESTIONS=(
  "问题属于记账合规、经营决策、还是资本结构；公司规模与阶段；业务是订阅制、项目制还是贸易制；是否多主体多币种。"
  "症状是不赚钱（利润表结构），还是赚钱但没钱（营运资金与现金转换周期），还是钱够但投错（资本配置）。"
  "每个数字是权责发生制还是收付实现制、含不含税、是否已确认；是系统导出还是手工；税务与政策类数字的发文年份。"
  "这是一个决策问题还是一个报表问题；如果是决策，哪些成本是增量的、哪些是沉没的、哪些是分摊来的。"
  "现有 cap table 与全面稀释口径、条款清单里的清算优先权类型与倍数、期权池扩容时点、是否有对赌或回购。"
  "要引用的方法（DCF、ROIC 门槛、SaaS 单位经济、Beyond Budgeting、Profit First 式分桶）各自的前提在这个场景是否满足；有没有更便宜的替代解。"
  "涉及的准则版本（IFRS 15/16/18、ASC 606、CAS 14/21）与生效安排；中国侧的申报时点、发票形态、付款期限、供应链金融限制等年度变量。"
)
declare -a DIM_SOURCES=(
  "本文 §1 的七个模型作分诊表；\`references/research/02-tools.md\` 的选型决策树给出阶段划分。"
  "本文 §1.1 与 §1.2；\`references/research/03-workflows.md\` 的 13 周现金流与关账两条流程。"
  "\`references/research/06-glossary.md\` 的术语与易混淆对照；官方发布口（\`mof.gov.cn\` / \`chinatax.gov.cn\` / \`ifrs.org\` / \`sec.gov\`）。"
  "本文 §1.3；\`references/research/03-workflows.md\` 的成本核算与定价、投资测算两条流程。"
  "本文 §1.7；\`references/research/03-workflows.md\` 的融资建模流程；\`references/research/06-glossary.md\` 的股权与融资术语组。"
  "本文 §7 的六派对照；\`references/research/04-canon.md\` 的争议节；\`references/research/01-figures.md\` 的观点对立。"
  "\`references/research/06-glossary.md\` B 节的准则与法规；发布机构官方页。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话锁定「这是一个 {层级} + {业务形态} 的问题」，并说明这个坐标排除了哪些解法。"
  "先给出判定与理由，再给解法。**跳过这一步直接给方案，是这行最典型的外行动作。**"
  "列「已确认口径」与「待确认口径」两栏，待确认项不进结论；税务类结论标注 \`last_checked\` 与发文号。"
  "明写「本结论用的是 {贡献边际 / 增量现金流 / 全成本} 口径，因为问的是 {哪类问题}」，并说明换一套口径结论会怎么变。"
  "给出三个情景下的创始人实得，再给条款谈判优先级；估值数字放最后。"
  "明写「本建议基于 {流派}，其前提是 {条件}；若 {条件} 不成立，改用 {替代}」。"
  "列出适用规则与生效时间线，标注 \`last_checked\` 与 \`Decay risk\`，不确定的明写「需向发布机构核实」，涉及具体税务处理的一律注明「请以官方公告与持证税务师为准」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
