#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for 企业财务与 CFO 视角.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="企业财务与 CFO 视角"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果  → 则 公司账面盈利却总缺钱，**则**去看现金转换周期与应收账龄，而不是先去融资；多数情况下钱被锁在应收和存货里 eviden
  • 如果  → 则 要决定「这笔投入做不做」，**则**只算增量现金流，沉没成本与已分摊费用一律不进模型 evidence: [T03-S0
  • 如果  → 则 有人用调整后 EBITDA 说服你，**则**要求看调节表，逐项问每一笔「加回」凭什么不是真实成本 evidence: 
  • 如果  → 则 在比较两家公司或两个方案，**则**先统一口径再比数字；口径不同的比较在这行等于没做 evidence: [T03-S0
  • 如果  → 则 拿到一份 term sheet，**则**先算三个情景下的退出瀑布，再谈估值数字 evidence: [T03-S031
  • 如果  → 则 要上一套财务系统，**则**先问「谁来维护这个模型、维护多久」，答不上来就继续用电子表格 evidence: [T02-

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a RULE_ACTIONS=(
  "公司账面盈利却总缺钱，**则**去看现金转换周期与应收账龄，而不是先去融资；多数情况下钱被锁在应收和存货里 evidence: [T04-S047, T03-S036]"
  "要决定「这笔投入做不做」，**则**只算增量现金流，沉没成本与已分摊费用一律不进模型 evidence: [T03-S024, T03-S025]"
  "有人用调整后 EBITDA 说服你，**则**要求看调节表，逐项问每一笔「加回」凭什么不是真实成本 evidence: [T01-S023, T03-S044]"
  "在比较两家公司或两个方案，**则**先统一口径再比数字；口径不同的比较在这行等于没做 evidence: [T03-S044, T06-S011]"
  "拿到一份 term sheet，**则**先算三个情景下的退出瀑布，再谈估值数字 evidence: [T03-S031, T03-S029]"
  "要上一套财务系统，**则**先问「谁来维护这个模型、维护多久」，答不上来就继续用电子表格 evidence: [T02-S002, T02-S060]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
